# Encrypt with: sops --encrypt --in-place secrets.yaml
apiVersion: v1
kind: Secret
metadata:
    name: nexus-env
    namespace: nexus
type: Opaque
stringData:
    GITHUB_WEBHOOK_SECRET: ENC[AES256_GCM,data:pnfpRS47DZuUORzgZcWXnKuPzmdQrLW5r47ACGBBQSqf53BbZoxUdo1NkJ6eUFO+RJysDBsUDHx6Ch0YLmcQwg==,iv:XTkAAFhkJKPV9CuUBylZQdH780TMSUW856zjRy87lXY=,tag:ZldWTjjY9n/tkwGq5gWIXw==,type:str]
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:PWIfQbxYLQl2k+tnXE1qr6c9oLw08kuI9kOPXoUoVbVbWg+JdH3suX6/OPlBJDqleGwA0YfNGaETC2eenKZTlgJWLERu2DdFVw==,iv:e+oVDWRjZCp3bk1C9xna1uEKk/+BjNPRsxpJKb+qU6g=,tag:9n+iEz9SGUG+BuFF9h1jMg==,type:str]
    TS_AUTHKEY: ENC[AES256_GCM,data:wxcax9hark4KaUBQfZ34qUP5dS+bu/Wwe4mZ6npjhZ+4sVSsvCTrVtV+F+Olo48EhbYGiirihtdMDmCOuA==,iv:aeC+pfU9bbb+X/jR33xQnmv1q5OpyIX3naENOzZPYrc=,tag:urJBQyR1W1yKe0ZmL/Ymjg==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:ugYAXatlqwQ7y2ifo1cumv/oZc+/HjBCd71GTG+HvDpbVhosv25zygnFVSnv8Qx6yklISlsECl+y++3JbEa3xvZ1T2RAqDLnUWrANRJ0/bBSrdYPGHJgn5GFbuyrhzUHUQD7OmUhJsxBau/WaJwRw1dUAw==,iv:ImgQhNvTWRIDgEdAdzXPGWeiodjDw9c9aAUzs44IBok=,tag:mhcScjieLK/1Hb2UTdjf9g==,type:str]
    GRAFANA_WEBHOOK_TOKEN: ENC[AES256_GCM,data:4idp2cIckZf+Ao0SlWOsObpboA+qMRDLIf9UtGjLVFOkA16R18slrTWNK/WyGj6PR/ADb6Oo/xE7leB5ZE8oJA==,iv:nG9aH6IafcNIafwD98sEYLi1Y1GYdajpAK16jIOVtFs=,tag:RxpH1Ty2qA5r2NZvslzqEg==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:J3x5TsUWOR9GqmtsMNo1EkjGyMBI3IypQuNyHVaQQu1mtwIRXJHfZJ7+LmhovNW7m2h7iprWkLDXp5JJwi/84eBoE2sHSjAUXEAGcOYMXCURwkVTbILSsCGxQylOZgNpm0IACCjeBXWsfpzpMKHqo6Tq6THB48rTL7lXAzbaIqbL1/Ho8MXVlQ58GBr/MoOBNKnBvO0TIPwSnOL6mAt7Yaw6eOU=,iv:fq5cpAE7B60qA/eR8fYvfl24UefD0t0qSUkB3rgTO74=,tag:8Nf9zoE3C4N7RnNAiiaiMw==,type:str]
    CURSEFORGE_API_KEY: ENC[AES256_GCM,data:A4OBMFreq0L1dOEuMFLzZjVW+Rvgj/EtI7Lw7lPjeGclwDaTYHehJjNchZ2744S3bfJiBKwrR+jOc9bUkIMz,iv:5bz5703ng70vjGJnnNe0GHNBvhyP4Tr/m3GkfKq+3vI=,tag:5MQiEwEpbL/9jrBx9eT0TQ==,type:str]
sops:
    age:
        - recipient: age1776wth2d8psy2swdcuw5t5ptj4hdegnjzh2eppz4gahas6waks7q37cf57
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxeXdyQkR4OHJxT0poUk5R
            U01aTWp6UURMZzNQRHQvWFl2RGRXaEJ5YVFJCjY0ZUlRaGtKT3hwWmRGSVNzdjZK
            Q0hjZE8rTTUyamhpZTNmckhoQm9MbDAKLS0tIEdTUktNWW41eWw2ZlFBb0RMcTJq
            alBQbjFmako4YVlNVWp1RWp3UGxsQ1EKciH3gpYZxwBCiMbIoJVhFmMNak+dWod1
            QAhaR5Xjja0l/aiETAXaosxeIAf8JY4QX/zsHwRvnSYABfos9CWFFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-16T06:59:23Z"
    mac: ENC[AES256_GCM,data:LdT9L2/h7jx9+QsjyTuGBRYqz1DYTMYqgLDpdrAAc1D8x6zXufhulN5RDyLMP2eOysZM3scv0zzDbvcmp9xCWi/UcThf3kshiKdKCQCklsQTXuEcMIv2O6VOS0PvBQNGETGU52gByAryRWIFfCBjwf5K6nh2zZL5uNTT3oZzWJA=,iv:qI2nUVD9VGKRuyxtb94lT9xi3Q7SnAmzOm1eo1GPWgk=,tag:+kRdEaT44rHkeazo/IQ69A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
