apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-nvidia-gpu-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: gpu-operator
  sources:
    - repoURL: https://helm.ngc.nvidia.com/nvidia
      chart: gpu-operator
      targetRevision: "v25.10.1"
      helm:
        releaseName: gpu-operator
        valueFiles:
          - $values/argocd/clusters/superbloom/infra/nvidia-gpu-operator/values.yaml
    - repoURL: https://github.com/saavy1/sb.git
      targetRevision: main
      ref: values
  ignoreDifferences:
    - group: nvidia.com
      kind: ClusterPolicy
      jqPathExpressions:
        - .spec
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - ServerSideDiff=true
      - RespectIgnoreDifferences=true
