apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: sops-store
spec:
  provider:
    sops:
      age:
        privateKeySecretRef:
          name: sops-age-key
          key: key.txt
