apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: infisical-infra
spec:
  provider:
    infisical:
      hostAPI: http://infisical.infisical.svc.cluster.local:8080
      auth:
        tokenAuthCredentials:
          accessToken:
            name: infisical-token-auth
            key: accessToken
            namespace: infisical
      secretsScope:
        projectSlug: infra
        environmentSlug: dev
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: infisical-data
spec:
  provider:
    infisical:
      hostAPI: http://infisical.infisical.svc.cluster.local:8080
      auth:
        tokenAuthCredentials:
          accessToken:
            name: infisical-token-auth
            key: accessToken
            namespace: infisical
      secretsScope:
        projectSlug: data
        environmentSlug: dev
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: infisical-nexus
spec:
  provider:
    infisical:
      hostAPI: http://infisical.infisical.svc.cluster.local:8080
      auth:
        tokenAuthCredentials:
          accessToken:
            name: infisical-token-auth
            key: accessToken
            namespace: infisical
      secretsScope:
        projectSlug: nexus
        environmentSlug: dev
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: infisical-media
spec:
  provider:
    infisical:
      hostAPI: http://infisical.infisical.svc.cluster.local:8080
      auth:
        tokenAuthCredentials:
          accessToken:
            name: infisical-token-auth
            key: accessToken
            namespace: infisical
      secretsScope:
        projectSlug: media
        environmentSlug: dev
