apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: argo-workflows
  namespace: argo
spec:
  interval: 5m
  chart:
    spec:
      chart: argo-workflows
      version: "0.47.4"
      sourceRef:
        kind: HelmRepository
        name: argo
        namespace: flux-system
  install:
    createNamespace: true
  values:
    singleNamespace: true
    server:
      authModes:
        - server
