apiVersion: ENC[AES256_GCM,data:Oqk=,iv:OxsS079vd2Ec//eQ9DSd0an8G4FvKTH4YUh64uneoUw=,tag:qB2HyUkSlLFQ54+B6LvgMA==,type:str]
kind: ENC[AES256_GCM,data:LLe3D8jh,iv:RnLucFgCvZ1qPX9m8v8F+AhxgtbpIc8eak4Cc9hvQJY=,tag:NnBe35YgrbCN+XWMNcU4Tw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:MWZsG9id42nZI4jlqy0=,iv:wbleURrE1zFciT1erV8cZEhEl3Ijltz9MQvjx8VisiY=,tag:0Iefy3vmi8NV3jTd+nVzcg==,type:str]
    namespace: ENC[AES256_GCM,data:kAP1fQA59qo=,iv:rs+DMkwvAdwNZsHTvyEADJqBvXFkbCwqp62dEfDK2lg=,tag:lDkxfmrjoStSiBQWkoegLg==,type:str]
stringData:
    users.yaml: ENC[AES256_GCM,data:52nR3vrh7+63K22iUrxU1kQjm6RYu5yME3idlI8CRW381nk/xUubpfC8DDcsXXN4kbQ/Wt4UTXpEpOh43JNnqk8tybmFOZ7jIBNj33P8oWU0nK26xf6tPl1eXEs/nGrF0Ibcc8xcT1NKOQiiHUg7hBFnfW75XZzE9/6a4b9RLOEoU+xmZi7D/9V6rFvZJgUJOqsHMiLSi+RVXqvZlnrjwiT/7zzlyzT8r7J0u2x6sdu0Ef0lQhg1OnN3zT+Ny4A=,iv:qIi9nNSWxsnQ7JSHNz76pfXcIDReLVp7WuADK0ndLeE=,tag:Czo3ShuhmFHLxAKLBuk4uw==,type:str]
sops:
    age:
        - recipient: age1776wth2d8psy2swdcuw5t5ptj4hdegnjzh2eppz4gahas6waks7q37cf57
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiT1dBR3FFTFNDYlNxejZZ
            UXJYUVpZZzlGdE9QbWErSFRXVk9LS1RCMWpvCmpHWk8yR0JEbzRBalZCSWlUeUN5
            TkgwK0dDcGI1VlFHZ1BVbWE1UEo2bkEKLS0tICtFY2dxczJmUVZ2b0FIWjVIeVR1
            TEd3WEIzY2FGekJmVDBUc2ZabFk0d0UKClvSyaVj9/R4fYMogvQazGNGdtj8nUoo
            x0oUqeavzPZiJHHp3MnhrfyKWz4siEG0OVOv9rHpDgfESE3evB2GVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-02T20:53:14Z"
    mac: ENC[AES256_GCM,data:dYyewGdsX5sHQuhJLNd9YW8WOqXQrePT9copbkMEkLXILvENeuhqy7sCylaM92qE7MdZXnqqoMsIKjk+noH7aomUihLjxYm8uI/30lYebDlKui9g1IMlSS/zp5LoKNxBbCdbT51+XrgHmNV86q3WqJWlW8Hd5D+ELfbRSELPIJI=,iv:8hCBvl/sl4nIjJ/2Uh+AcW2Lplbb2cU2YAEXI/mmNV0=,tag:jX3E/iYe6ytoZv8mDQ04aw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
