apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ddns
  namespace: ddns
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 4.5.0
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      ddns:
        type: deployment
        containers:
          main:
            image:
              repository: favonia/cloudflare-ddns
              tag: latest
              pullPolicy: IfNotPresent
            env:
              DOMAINS: saavylab.dev,mc.saavylab.dev,auth.saavylab.dev,nexus.saavylab.dev,watch.saavylab.dev,shows.saavylab.dev,movies.saavylab.dev,downloads.saavylab.dev,fbi.saavylab.dev,indexers.saavylab.dev,subtitles.saavylab.dev
              PROXIED: "true"
            envFrom:
              - secretRef:
                  name: ddns-env
            resources:
              requests:
                cpu: 20m
                memory: 64Mi
              limits:
                cpu: 100m
                memory: 128Mi
