# Encrypt with: sops --encrypt --in-place secrets.yaml
apiVersion: v1
kind: Secret
metadata:
    name: ddns-env
    namespace: ddns
type: Opaque
stringData:
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:dj/lhpqZdwQuFQBr8v4hLUGc0AlXBdhbJZ/zbiTc6bM8F71MfI39Yw==,iv:bkjn+bEVL4ate2VE/Pnp7Am9No7/zIBxOa2A8d2+DRI=,tag:H6Opu+bk3kZLv3yQpe88ow==,type:str]
sops:
    age:
        - recipient: age1776wth2d8psy2swdcuw5t5ptj4hdegnjzh2eppz4gahas6waks7q37cf57
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYc09WWFlWT0hRVjRqamtE
            dkhpMGVudmJCRHQ4ZkpBMHJDNFNtMlYzVlM0ClMyRHhuazgzckt3dytIcUdsdEpE
            UWxrWnJOYThKMHlkR2VWZnNobVVXWEUKLS0tIFV1eGZReDdFSnZtMkx6cHEwWldo
            QjdGVEJmV08zZWFwRnQwVUFnT3JBL0kK8GL3kapparWdEghW2ujb1LrF8p1G1tWK
            6psEW3tI9suvSuUDhWSVaVVo/WQbbHKUgDTV+XGaoNmCnmw7zwCqsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-14T20:01:50Z"
    mac: ENC[AES256_GCM,data:mcT6Aomuqpnz2vGCCdnjPaLNSEM42aVFsVvwV+3fmem4LTVxkSbGjo7UHOVu0jDxPwoncPeo4o/YaKDv9z7JJogFqR4Veobz/62ONphtUXZ9kdXOKKYN3lMC8ycAQajscKPvvB0siFigNgbGfMkHPSN6LYaH7gSNItfLa+6EaDc=,iv:afJl9VqhtIdxUOMnjL4NPm1fPBf1H88lYroH6QeyeFg=,tag:NkTryGUpvyd0cnT1Xl2P3A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
