apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nexus-bot
  namespace: nexus
spec:
  interval: 1m
  chart:
    spec:
      chart: app-template
      version: 4.1.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        replicas: 1
        containers:
          main:
            image:
              repository: ghcr.io/saavy1/nexus-bot
              tag: latest
              pullPolicy: Always
            env:
              NODE_ENV: production
              ELYSIA_API_URL: http://nexus.nexus.svc.cluster.local:3000
            envFrom:
              - secretRef:
                  name: nexus-bot-env
    service:
      main:
        enabled: false