apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-sparkdash
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: sparkdash
  sources:
    - repoURL: https://bjw-s-labs.github.io/helm-charts
      chart: app-template
      targetRevision: "4.5.0"
      helm:
        releaseName: sparkdash
        valueFiles:
          - $values/argocd/clusters/superbloom/infra/sparkdash/values.yaml
    - repoURL: https://github.com/saavy1/sb.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/saavy1/sb.git
      targetRevision: main
      path: argocd/clusters/superbloom/infra/sparkdash/resources
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - ServerSideDiff=true