apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nexus-embeddings-worker
  namespace: nexus
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: "4.1.1"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        # Can scale horizontally for more throughput
        replicas: 1
        containers:
          main:
            image:
              repository: ghcr.io/saavy1/nexus-embeddings-worker
              tag: latest
              pullPolicy: Always
            env:
              NODE_ENV: production
              # External services
              VALKEY_URL: redis://valkey.valkey.svc.cluster.local:6379
              QDRANT_URL: http://qdrant.qdrant.svc.cluster.local:6333
            envFrom:
              - secretRef:
                  name: nexus-env
            # No HTTP probes - worker doesn't expose HTTP
    # No service needed - doesn't expose HTTP
    service:
      main:
        enabled: false
