apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nexus
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./flux/clusters/superbloom/nexus
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
    - name: data
  wait: true
  timeout: 10m
