apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ha-registry-pull
  namespace: home-assistant
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: infisical-infra
    kind: ClusterSecretStore
  target:
    name: ha-registry-pull
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
      data:
        .dockerconfigjson: >-
          {"auths":{"registry.saavylab.dev":{"username":"{{ .username }}","password":"{{ .password }}","auth":"{{ printf "%s:%s" .username .password | b64enc }}"}}}
  data:
    - secretKey: username
      remoteRef:
        key: ZOT_USERNAME
    - secretKey: password
      remoteRef:
        key: ZOT_PASSWORD
