apiVersion: v1
kind: Secret
metadata:
    name: infisical-secrets
    namespace: infisical
type: Opaque
stringData:
    AUTH_SECRET: ENC[AES256_GCM,data:KBHnxvjdkL31iJVF44Nphi6CMDQwxiz9yAUEmQIII8/AmAMxC3EK33KCqM0=,iv:qrOy4UNfey4EftmgiDuTRTYf7nZEePJL7JnNiqKwFNY=,tag:4qKdws49wHaRB6IGGfMKUg==,type:str]
    ENCRYPTION_KEY: ENC[AES256_GCM,data:ib08mXDinUFkBUcBcqBscAG0oalkPLt/hV/s8sXH1n8=,iv:mvxTT4VnMD/XSqlyMHER/yGrWqEC4voAQtAhBwxF3PA=,tag:gZqqGIQpwIz/pkjlbggCgg==,type:str]
    SITE_URL: ENC[AES256_GCM,data:vWGcXXzRCeRecul9T/sPFUEupAe7ZaPBmaG2rWe5,iv:orLlEST91lhKy9hUiAGBUMIa0+6uSxBzB5EojlN41yg=,tag:UlN1UluQDOfHFNpNkpy1zA==,type:str]
sops:
    age:
        - recipient: age1776wth2d8psy2swdcuw5t5ptj4hdegnjzh2eppz4gahas6waks7q37cf57
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtSTA4R0RtSDBCaXU3NGpv
            MEhXU1BqbGtRMGxoWGdlY2VEcmJPaWcyNVRzCitzenJRWVcvYjVFUTdQQ1cxVStM
            WW1PdlRNVVE2V2FsaGFscVd6RnB1bmMKLS0tIFZ0Vkl6dUw2bGxac2JTdGFyVyt0
            a21jUjg4aGRxSGlrU3lKalUvSlNlSncKJtbsWtLfhR7SAN1xPBjTdj8mZrgBOyeK
            X5qVYku4/Yb6o8JFgi9GtKYf1udKawSY1/b3aF1qsNkljRZztXyWhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-27T05:30:50Z"
    mac: ENC[AES256_GCM,data:c7J7O6TptUiOPXKlwdLXbZHukui27GriCc3kql+6C5idR7zH6bvz1UX4q78EwojxfBw7y2nN7+Icwg6xodC0wGKscum/uL2E2zfCwdpstvH6I15C2aah4G2vnypMhQBxFvmTU3p0xGNz0GMdFUnueDIfwKnFG2xrky8V1NEFL2w=,iv:XpoDcksu7oe/N0sQWKeavOHART66CD0LD31+A0ShoJ0=,tag:cOC3SzBnmGqxMhOhAN/rAQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: infisical-bootstrap-credentials
    namespace: infisical
type: Opaque
stringData:
    INFISICAL_ADMIN_EMAIL: ENC[AES256_GCM,data:13hPxgY8BpLvo8KBaLla+TSZqA==,iv:zO8yULaeTZliAN4WA19XjyNzOxS5PfOjIjapBKLWSXo=,tag:TpDF62gpbuC3hQucHMaviw==,type:str]
    INFISICAL_ADMIN_PASSWORD: ENC[AES256_GCM,data:NWa516Sibl7I4YxeB/G0P9Wq6dk2g91wF8GXH+G/5Wc=,iv:FCaNZdGfvy9ytFWzS7byLSfdlpvdEimadBK2Gx1HBdw=,tag:R6ibZy+f9W4YUlLD/mQG4A==,type:str]
sops:
    age:
        - recipient: age1776wth2d8psy2swdcuw5t5ptj4hdegnjzh2eppz4gahas6waks7q37cf57
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtSTA4R0RtSDBCaXU3NGpv
            MEhXU1BqbGtRMGxoWGdlY2VEcmJPaWcyNVRzCitzenJRWVcvYjVFUTdQQ1cxVStM
            WW1PdlRNVVE2V2FsaGFscVd6RnB1bmMKLS0tIFZ0Vkl6dUw2bGxac2JTdGFyVyt0
            a21jUjg4aGRxSGlrU3lKalUvSlNlSncKJtbsWtLfhR7SAN1xPBjTdj8mZrgBOyeK
            X5qVYku4/Yb6o8JFgi9GtKYf1udKawSY1/b3aF1qsNkljRZztXyWhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-27T05:30:50Z"
    mac: ENC[AES256_GCM,data:c7J7O6TptUiOPXKlwdLXbZHukui27GriCc3kql+6C5idR7zH6bvz1UX4q78EwojxfBw7y2nN7+Icwg6xodC0wGKscum/uL2E2zfCwdpstvH6I15C2aah4G2vnypMhQBxFvmTU3p0xGNz0GMdFUnueDIfwKnFG2xrky8V1NEFL2w=,iv:XpoDcksu7oe/N0sQWKeavOHART66CD0LD31+A0ShoJ0=,tag:cOC3SzBnmGqxMhOhAN/rAQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
