apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - external-secrets/
  - cert-manager/
  - caddy/
  - ddns/
  - home-assistant/
  - tailscale-operator/
  - alloy/
  - loki/
  - tempo/
  - kube-prometheus-stack/
  - nvidia-gpu-operator/
  - hermes/
