apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - alloy/
  - argo-workflows/
  - buildkit/
  - authelia/
  - caddy/
  - cert-manager/
  - ddns/
  - external-secrets/
  - home-assistant/
  - infisical/
  - kargo/
  - kube-prometheus-stack/
  - loki/
  - nvidia-gpu-operator/
  - tempo/
  - zot/
