apiVersion: v1
kind: ConfigMap
metadata:
  name: caddyfile
  namespace: caddy-system
data:
  Caddyfile: |
    # Global options
    {
        email jayson@saavylab.com
    }

    # Authelia portal - no forward_auth (would cause redirect loop)
    auth.saavylab.dev {
        reverse_proxy authelia.authelia.svc.cluster.local:80
    }

    # Nexus dashboard - protected with forward_auth
    nexus.saavylab.dev {
        # GitHub webhook bypasses auth (signature verified in app)
        # Other webhooks (alertmanager, etc.) use internal ClusterIP
        @github_webhook path /webhooks/github
        handle @github_webhook {
            reverse_proxy nexus.nexus.svc.cluster.local:3000
        }

        # Everything else requires auth
        handle {
            forward_auth authelia.authelia.svc.cluster.local:80 {
                uri /api/authz/forward-auth
                copy_headers Remote-User Remote-Groups Remote-Email Remote-Name
            }
            reverse_proxy nexus.nexus.svc.cluster.local:3000
        }
    }

    # Jellyfin - no forward_auth (uses built-in auth, easier for TVs/Xbox)
    watch.saavylab.dev {
        reverse_proxy jellyfin.jellyfin.svc.cluster.local:8096
    }

    # Health endpoint (optional - for k8s probes on the caddy service itself)
    :80 {
        respond /health 200
    }
