apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: games
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: game-servers
  source:
    repoURL: https://github.com/saavy1/sb.git
    targetRevision: main
    path: argocd/clusters/superbloom/games/resources
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
