apiVersion: v1
kind: Secret
metadata:
    name: homelab-api-env
    namespace: hermes
stringData:
    JELLYSEERR_API_KEY: ENC[AES256_GCM,data:F18ixRnos4FeXXZjYJHYtHrA+MIy6So46QjNg3g/H4kdVJJzwKib6Z/UEevVShYfFc2ePuZTjHVmBVbcKN4OYp3g7ig=,iv:zpI4TbORYIaEppDC4tzOkirtSeEkjII5b5/+USZpoTo=,tag:r2nzqQ7V8E00hk5MZ2fiog==,type:str]
    SABNZBD_API_KEY: ENC[AES256_GCM,data:KV9gaxhMy6gjsPktMmn5CxuhVgybzicf8lezn9XVQ8g=,iv:SjOL4zr55S+7UcIevv09v4+RKj/H4Mvzp0/XufjSjzU=,tag:psmH+FHM2WorbEPF0LoIYQ==,type:str]
    JELLYFIN_API_KEY: ENC[AES256_GCM,data:1DoHJiu15vZkDmSnrk2A3Xil2l+nBUj0ocsQQsaZhWc=,iv:ByZOiVUjWW4kwKBll/weHZZSPVzvoGCvfoU67JdiMvc=,tag:NCrpnt4aUOB7x3hJYBoLAg==,type:str]
sops:
    age:
        - recipient: age1776wth2d8psy2swdcuw5t5ptj4hdegnjzh2eppz4gahas6waks7q37cf57
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqTzVsZkNKYkQ3VGc2eEFI
            SmRCdTdwR3A4V2RaVFZIU3FGeEcvSjQ3cldZCk5hWHFFSlFCakUweVVnY1YwZXlw
            SC9uYTlIZ25mL2FBQ3Z0eE5RNG9JMkEKLS0tICtzdm42NzFaRDFOSUlGZE5pUDhl
            SjQ5ak1vVk9XQzVKeThOM1gwYzNtcHcKpOi85N6nzbXKRFTyJ535eXRtn6hdsO12
            N529CGTbfAdign17ee2jDExNWPiFskp+0om7zzFkRUPK/w95EAKiTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-19T23:19:54Z"
    mac: ENC[AES256_GCM,data:Bh9GiJVOcY6oTvhaMa8xmooeE6mjvKf8pe028tjgPxg89QtX7X1WQOu2syuxKbWLRNGh+fEUpM5wBuchdqzqaNBOOo5kM+3ul9WCBVBFejm5McrPcFCU/6l0xVBYmXOiMHgyoaPlfMy3cjLBY5syr9nYCmoewMG7Jn6WtiQBllc=,iv:ugw51SARsHVVlc4+6RqQD3rOelJoYGTGkyLN+mx1sh4=,tag:ztbM+fxV2L0p80PxJRpE3Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
