apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana
  namespace: flux-system
spec:
  interval: 30m
  url: https://grafana.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana-k8s-monitoring
  namespace: alloy
spec:
  interval: 5m
  chart:
    spec:
      chart: k8s-monitoring
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    cluster:
      name: superbloom

    destinations:
      - name: grafana-cloud-metrics
        type: prometheus
        url: https://prometheus-prod-36-prod-us-west-0.grafana.net/api/prom/push
        auth:
          type: basic
          usernameKey: PROMETHEUS_USERNAME
          passwordKey: GRAFANA_CLOUD_TOKEN
        secret:
          create: false
          name: grafana-cloud-credentials
          namespace: alloy

      - name: grafana-cloud-logs
        type: loki
        url: https://logs-prod-021.grafana.net/loki/api/v1/push
        auth:
          type: basic
          usernameKey: LOKI_USERNAME
          passwordKey: GRAFANA_CLOUD_TOKEN
        secret:
          create: false
          name: grafana-cloud-credentials
          namespace: alloy

      - name: gc-otlp-endpoint
        type: otlp
        url: https://otlp-gateway-prod-us-west-0.grafana.net/otlp
        protocol: http
        auth:
          type: basic
          usernameKey: OTLP_USERNAME
          passwordKey: GRAFANA_CLOUD_TOKEN
        secret:
          create: false
          name: grafana-cloud-credentials
          namespace: alloy
        metrics:
          enabled: true
        logs:
          enabled: true
        traces:
          enabled: true

      - name: grafana-cloud-profiles
        type: pyroscope
        url: https://profiles-prod-008.grafana.net:443
        auth:
          type: basic
          usernameKey: PYROSCOPE_USERNAME
          passwordKey: GRAFANA_CLOUD_TOKEN
        secret:
          create: false
          name: grafana-cloud-credentials
          namespace: alloy

    clusterMetrics:
      enabled: true
      kepler:
        enabled: true

    annotationAutodiscovery:
      enabled: true

    prometheusOperatorObjects:
      enabled: true

    clusterEvents:
      enabled: true

    nodeLogs:
      enabled: true

    podLogs:
      enabled: true

    applicationObservability:
      enabled: true
      receivers:
        otlp:
          grpc:
            enabled: true
            port: 4317
          http:
            enabled: true
            port: 4318
        zipkin:
          enabled: true
          port: 9411

    autoInstrumentation:
      enabled: true
      beyla:
        deliverTracesToApplicationObservability: true

    profiling:
      enabled: true

    integrations:
      alloy:
        instances:
          - name: alloy
            labelSelectors:
              app.kubernetes.io/name:
                - alloy-metrics
                - alloy-singleton
                - alloy-logs
                - alloy-receiver
                - alloy-profiles

    alloy-metrics:
      enabled: true
      remoteConfig:
        enabled: false

    alloy-singleton:
      enabled: true
      remoteConfig:
        enabled: false

    alloy-logs:
      enabled: true
      remoteConfig:
        enabled: false

    alloy-receiver:
      enabled: true
      remoteConfig:
        enabled: false
      alloy:
        extraPorts:
          - name: otlp-grpc
            port: 4317
            targetPort: 4317
            protocol: TCP
          - name: otlp-http
            port: 4318
            targetPort: 4318
            protocol: TCP
          - name: zipkin
            port: 9411
            targetPort: 9411
            protocol: TCP

    alloy-profiles:
      enabled: true
      remoteConfig:
        enabled: false
