# Encrypt with: sops --encrypt --in-place secrets.yaml
apiVersion: v1
kind: Secret
metadata:
    name: grafana-cloud-credentials
    namespace: alloy
type: Opaque
stringData:
    GRAFANA_CLOUD_TOKEN: ENC[AES256_GCM,data:V1rFEHSLYkn07DcU6IRu/FhXP/kPojvnQdtpGATojVrbVBYVrhzXsixUO+A6WJTR5pHlp6L+3hoaNl0bgJx6UxEwL07Qm8hObRRCbzi8qFrUMOglMD90trq7BA1doh8p4JDWXaZ6xaZ7PfuPkfYJt0HRgpJ5d58OVm14l/IhjrvjMfAvm6lvDwMPov5Yh7anmx3h/sXMZRE=,iv:NNTo0XK8DO5MuKc5sLUJB71tGKdiiRU+Ztj7WFFpqZA=,tag:rEaqbnL9k/+7mOouJG+hxQ==,type:str]
    PROMETHEUS_USERNAME: ENC[AES256_GCM,data:2+9l1hmHBA==,iv:k/tkzg3b8gjyB6CFy5rAcNTXeZhcaCV5i7EQtlzIQnU=,tag:YhVkqtgBFWr5Sj/ygop2jA==,type:str]
    LOKI_USERNAME: ENC[AES256_GCM,data:v+hnvBopNQ==,iv:ctRFnFIOTABud4dum9Watdj710ynKV1hutgR4Pp4zQo=,tag:1dXU4lgvkha1QobbB0PDKw==,type:str]
    OTLP_USERNAME: ENC[AES256_GCM,data:pcCPzow5bg==,iv:JFFEuNQnkDGoBHKK7U3qAtVbDgWrvGyupcY5yDEBe2M=,tag:Um+FhZyvOBrQKPM1IzahJw==,type:str]
    PYROSCOPE_USERNAME: ENC[AES256_GCM,data:zyUtVVBdYQ==,iv:mYQEUkfjszzfv+5MIeU/8tM9XxLoF7IaMmmyIAeFd0w=,tag:fvpAa555pQwDsZJAiRYPtg==,type:str]
sops:
    age:
        - recipient: age1776wth2d8psy2swdcuw5t5ptj4hdegnjzh2eppz4gahas6waks7q37cf57
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaU2kwaHhhR2FzcnJNR0J0
            dkExRXNUNzBKSWFGUmJLQ2tSb0F5TExvQVZJCnhxYzM1Zk5XajdjVjlqbDYrd1Np
            ZUtwNVBwV3BxUVQ3T3dQWThQOGtza0UKLS0tIHNRREgxd2dUY0t4aHZCREs0VzZU
            alphSmZVMGx2TnBpYlJRb01ET2VIRDgKR3jcZz+gjm5WiBEyohn9fECQeDPTmD2w
            4Cpo2OXOBOofTbzRdkQVRqiWk5B0jLfSRP+Q3DVSIpDHjJuRH9R4ow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-14T20:03:33Z"
    mac: ENC[AES256_GCM,data:vAIesPqOSzjgeq4FPUzVHdnrCcEwKABRYqLwryvFzuoJLaOkao4lZdJF0CS349E2slZN3r5I4bOG0gsvOqsDY0VAc/kRkLLGna+liccjdQNvEHHzSquAcNSmrwrPU1Aubzbz8CfDU7iX4MwZzlmnK0/cqtupkGt7v59lHKXUgw0=,iv:kc3Twa3ZKUnM1MKW2GfmFE4Bvpawv5QrWxIINN6CKkA=,tag:H3P3praO1vqW9LDiziIVCA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
