apiVersion: v1
kind: Secret
metadata:
  name: github-webhook.service-account-token
  namespace: argo
  annotations:
    kubernetes.io/service-account.name: github-webhook
type: kubernetes.io/service-account-token
