apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argo-workflows-webhook-clients
  namespace: argo
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: infisical-infra
    kind: ClusterSecretStore
  target:
    name: argo-workflows-webhook-clients
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      engineVersion: v2
      data:
        github-webhook: |-
          type: github
          secret: "{{ .githubWebhookSecret }}"
  data:
    - secretKey: githubWebhookSecret
      remoteRef:
        key: ARGO_WORKFLOWS_GITHUB_WEBHOOK_SECRET
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
