apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - argo-workflows-server-rbac.yaml
  - github-webhook-rbac.yaml
  - github-webhook-token-secret.yaml
  - workflow-runner-rbac.yaml
  - zot-push.enc.yaml
  - argo-workflows-webhook-clients.enc.yaml
