apiVersion: ENC[AES256_GCM,data:kwU=,iv:2DcTZXmeEhtnfiWrk4JZoRmb8ZNoWaAA6bUNWAxbaMg=,tag:FMRh9Kx5lQr11VboWEbFyg==,type:str]
kind: ENC[AES256_GCM,data:X9uh6xig,iv:Ovc+kJ9qjl5hewGX0Jplnqdhp7Y+ZgsUmjc0mBcQaLY=,tag:DoM6v0uV17ZeJY2Fn/AYuA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:gxFGLOkEPrqeXMi/B18=,iv:0cCRnnjJfJaQYtOTumfdgXh0biCKHovhdfqdyA7rwy0=,tag:FdAsBxg3Ovr2UdC3EDfZFw==,type:str]
    namespace: ENC[AES256_GCM,data:N3TnryW76p9m,iv:3eelNRBFJvGpnwd9ZrwWVxPa/z24VZ/aN8Bur7BOKJk=,tag:BOhMH76uZpwlSANw4VQOLQ==,type:str]
stringData:
    client_id: ENC[AES256_GCM,data:G/0DUUkEhZFVCfMBaTqRT9+A5/5hH4p1IImUyAcA7w0=,iv:Krls6nZr/hy7TpTcMzZCAb91e31EjOkRkmuIe4fQBP0=,tag:bh1+g+8JZi3QV2nTRi9rGA==,type:str]
    client_secret: ENC[AES256_GCM,data:75Rnml9+dtahq2CoVaxo4VuCX6rxtRm3LqYBwTtXAZhjRSor,iv:/goFnij6k38Pk6iW19NN7ZVJKi2Q6L2DDaD92H0O5E4=,tag:9Oi5KYbVe6wowqsGWiFn3g==,type:str]
sops:
    age:
        - recipient: age1776wth2d8psy2swdcuw5t5ptj4hdegnjzh2eppz4gahas6waks7q37cf57
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBacktLMWV2eHIxZ2VNZHc0
            eWNLYWFCV3FzQVZ0eUgvQWt0VUliVTQvdlU4Cnk1Wm1nMVM4dGcrMEo4ZjEvS1Z5
            SEUyQzFOclMvT0NueStneSsrd3dqZ3cKLS0tIGljeTJpYnpja2w4RU1jNFd4cEgv
            ZjZxVlM1L0FhSTZuRHNXc1RlS3JpU2MKWvN6RacFDaaWj33rhU0xFVK0/3UA2DOz
            d3wJ1MKs04jDtpQziyKduNJU45IeS/IN80+2IIUhjjlnq2kZWA9gUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-02T21:35:07Z"
    mac: ENC[AES256_GCM,data:pEIXmLJcRT2EHobUbdRGwsovJWiEyzTHpLnH0jh8bz46nQXBjmLKMIM0LRV1edHMeetYrEXB81qo8bazHVkRiZ+8jokDn8FlmlLpg6fT5+TLLf+0urC8NAHiORsXJXwJIBPxghVf0GBKyY+Vparb8Oj7G4oJ9u+zKgP+hTRqAJ4=,iv:R7/NZ4xlKpUNETEjhbeNAd3bvuGLsaFy3Gy0/X3vn5U=,tag:hl7UwjuJAw6alj0KOcoo2g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
