apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: tailscale
stringData:
    client_id: ENC[AES256_GCM,data:IJhG+sBlwfv8ebvW++wks+M=,iv:VwHaBERDHkKdu4D3BE1Z3SXy49KOu2UUh4priN776Lk=,tag:xgHY1bMhOK7n/gspmAsTgA==,type:str]
    client_secret: ENC[AES256_GCM,data:1aSQFgTpdfWR7PrRCTX2aXUYXNHgtkadKtk9iOHhnYBRjaiMSlUnz3Ur6Tq2L8iDDobfAsyY0uiianUABWjCWQ==,iv:BwO9wPWhxvjDTVL+tSf1b05meadzS+H4iOFL8ehvqAo=,tag:Wcv8PFvcenH+slUdS4aFKQ==,type:str]
sops:
    age:
        - recipient: age1776wth2d8psy2swdcuw5t5ptj4hdegnjzh2eppz4gahas6waks7q37cf57
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0b2ZUa1B1dEdDT0hqNzZz
            Wnp3N2JwVnRBMmdsLzU0NnhTZmNIWUJ5SUFZCkF2bENiazZ4RDhJZC8ya0JXUUNt
            ekkxaTlXUFNiRlhMeUJzOUNjd2RRWEkKLS0tIDZSNkQyOEh0eHA2VFAvL3dzQlh2
            QVp1ZGhSMUN5VXNuRDkwTDNxSDByemsKAzUzrYljv1zW23+YSrn5w0YAH9agp1PN
            iBSUzKrZlk/S+fVHvjCMyizrDCSYzFshScKYnrp8GR8qBSnw1X9AwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-02T21:56:37Z"
    mac: ENC[AES256_GCM,data:mAQNoa9p+FGJN942zCtiitWI5LUQ15WfsyakUdvW/krAm5uwOxJK04Vh6jrz3D/DdsDJdtdiatAImXiZ3tkO39sD5JExIb+a0wCwr+pyYB9osLEu0FUtlgamlcypjuGMA7xCwUiZmrq/ckUfMeQQPFBo/tu5jnBObze04VKo3ls=,iv:k+NUfNWNyAgKoGBkzsrUqpzgQxP7KE3mWicGi9yNn6s=,tag:lwCQrgfsJ42/SZf39L/2GA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
