apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qdrant
  namespace: qdrant
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: "4.1.1"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: qdrant/qdrant
              tag: v1.13.2
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /readyz
                    port: 6333
                  initialDelaySeconds: 10
                  periodSeconds: 10
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /readyz
                    port: 6333
                  initialDelaySeconds: 5
                  periodSeconds: 5
    service:
      main:
        controller: main
        ports:
          http:
            port: 6333
          grpc:
            port: 6334
    persistence:
      storage:
        enabled: true
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 10Gi
        storageClass: local-path
        globalMounts:
          - path: /qdrant/storage
