apiVersion: v1
kind: ServiceAccount
metadata:
  name: nexus
  namespace: nexus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tailscale
  namespace: nexus
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tailscale
  namespace: nexus
subjects:
  - kind: ServiceAccount
    name: nexus
    namespace: nexus
roleRef:
  kind: Role
  name: tailscale
  apiGroup: rbac.authorization.k8s.io
