apiVersion: v1
kind: ServiceAccount
metadata:
  name: nexus
  namespace: nexus
---
# Local role for tailscale secrets
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tailscale
  namespace: nexus
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tailscale
  namespace: nexus
subjects:
  - kind: ServiceAccount
    name: nexus
    namespace: nexus
roleRef:
  kind: Role
  name: tailscale
  apiGroup: rbac.authorization.k8s.io
---
# Cluster-wide read access for kubectl operations
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nexus-cluster-reader
rules:
  # Core resources - read
  - apiGroups: [""]
    resources: ["pods", "pods/log", "services", "endpoints", "namespaces", "nodes", "events", "configmaps", "persistentvolumeclaims"]
    verbs: ["get", "list", "watch"]
  # Apps - read
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets", "daemonsets", "replicasets"]
    verbs: ["get", "list", "watch"]
  # Flux resources - read and reconcile
  - apiGroups: ["source.toolkit.fluxcd.io"]
    resources: ["gitrepositories", "helmrepositories", "helmcharts"]
    verbs: ["get", "list", "watch", "patch"]
  - apiGroups: ["kustomize.toolkit.fluxcd.io"]
    resources: ["kustomizations"]
    verbs: ["get", "list", "watch", "patch"]
  - apiGroups: ["helm.toolkit.fluxcd.io"]
    resources: ["helmreleases"]
    verbs: ["get", "list", "watch", "patch"]
  # Pod management for restarts
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["delete"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets", "daemonsets"]
    verbs: ["patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nexus-cluster-reader
subjects:
  - kind: ServiceAccount
    name: nexus
    namespace: nexus
roleRef:
  kind: ClusterRole
  name: nexus-cluster-reader
  apiGroup: rbac.authorization.k8s.io
---
# Full access to game-servers namespace for managing game server resources
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nexus-game-servers
  namespace: game-servers
rules:
  - apiGroups: [""]
    resources: ["persistentvolumeclaims", "services"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nexus-game-servers
  namespace: game-servers
subjects:
  - kind: ServiceAccount
    name: nexus
    namespace: nexus
roleRef:
  kind: Role
  name: nexus-game-servers
  apiGroup: rbac.authorization.k8s.io
