# Encrypt with: sops --encrypt --in-place secrets.yaml
apiVersion: v1
kind: Secret
metadata:
    name: nexus-env
    namespace: nexus
type: Opaque
stringData:
    GITHUB_WEBHOOK_SECRET: ENC[AES256_GCM,data:m83on9FQBGj2EXHEtZi6gZpPTGeAZtlGZKB1Alxwx5sUFgaLrAe2VxdX48MXgEn4N9ogJ9sXP7ZjLfMzaGnHWw==,iv:2yj3gAloMiTZQCVC2nvXOGLeD/zH7E0pmVDxt5Rz5No=,tag:uucTrof/qgCiLTyxuVGOag==,type:str]
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:NQ8wLFfgqdPad2Ok2EbEtSqvEdzTbAgey8EHEr1hDe2cuM/NU6PSvh/2K7KCYlDmeJcFKWLXxgAfaUS8PC+JwQw3932JbHe67g==,iv:4FVSHC3d49maVwoAxDq4Qvc2PY95Rh4qa+LmxKzglWU=,tag:f15XbvICB16T2cJ3i9+QnQ==,type:str]
    TS_AUTHKEY: ENC[AES256_GCM,data:s2RMueIA9NA2cMU0LED7Ll18KXnpLK4Z7uzVTtRyOxgl0aCUlDUv8i3eELJMQsyrDBvxthtQ/wUoFP2pyg==,iv:JDobTLNksjwx9mliMSIFfsLMhy1v9Z2CMlHuU85txFQ=,tag:1DodRmNbzR5Yghope0qlxw==,type:str]
sops:
    age:
        - recipient: age1776wth2d8psy2swdcuw5t5ptj4hdegnjzh2eppz4gahas6waks7q37cf57
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuY1c2RXQveEhzWE9ISUxZ
            bk0wVUQ1ZkJidS9RSjJ1WUNjV3J1NHJRM0ZBCndNZzR2dGZjclo3TlFVa2FwdXBU
            SjVrY29xU3JtbHRockkremxzb3d6SmMKLS0tIFZBTVZjcjhvQlBvR2xnQVEzQUVx
            MnNydWRyNXFvUzdpZmcvdjBobVVQQVEKXX6L4ObMe7sr3oJ4X7hy/u+GjBlF0MoV
            DGEXaw6CxEwMzV5gIPnNoG9HLpM3IGytCzI4XsvXZTWeznngGj8RRA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-14T19:57:40Z"
    mac: ENC[AES256_GCM,data:JnL2ntRP/New2hXhzqCre7zwgsf/xyD6ez2sH8l0m/ZZPHCAQ4JnVaVqiP8rFdxv0fVaL3ziYBU4hIyo2T1uQaJHUWv8aqBXsi0h+fY+d06jtAoNzfC4GVcpoewKjBSob4Pv40oODFn61JxAIwGxt9YbZHs9KtR4ofmCl38KW7w=,iv:nQos16Pn646WrG6dMTof+0Ayu+py/75/DZqR12117/8=,tag:+r81Ne2VwTzqbbXIvk6ETw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
