# Encrypt with: sops --encrypt --in-place secrets.yaml
apiVersion: v1
kind: Secret
metadata:
    name: nexus-env
    namespace: nexus
type: Opaque
stringData:
    GITHUB_WEBHOOK_SECRET: ENC[AES256_GCM,data:jL4s2kxZ9z0LCec8WsqjJZFZKwd/+VnAXdwDublVmqBk4Do3YCDJBOfzekuCTbNOWPwlB+4GspKHLNBFbbyqHQ==,iv:yBkklowE3DQ5ZH0TB39WH38JvJ0yRTAbAuEALlJgNUo=,tag:iy2qeC0MX5GrSf1QvB0jRw==,type:str]
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:Vq4oSJE1v7PaKy2lFrb9s2ZUmztxSvt3q84Q20IDuN8VDt4htEQ/u/TFgmefRmApTic2G/pX0BkxqF9OwEEIDdcOKVoqLYUc0A==,iv:8V3+a8gSuHkyH68B6Pm15Fe9hFhM9J1N826KKeN7+aY=,tag:WV1TqE4DvIbdsd1Pvxl6cQ==,type:str]
    TS_AUTHKEY: ENC[AES256_GCM,data:Q97UzVC/+D6aPESLjh9aPnuJL5PpCuyzVT/kIJcYZm4ETmIHq0W4lqC4kN21WJzFkeJYmIY6eJR+8kbekw==,iv:xF88zCsIRtTBCwq6/BmVDRuTdM9v0+Va1r4PIjuyUi8=,tag:BDH8SsizNRsI1RZWfopIvw==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:VlB9M60yERr5bw8LraeKpmsxG22hv74BRZl+3k335VI9N9xIB1x5CCFg9lEIGiBIW1sPOCF+wkLOUBxiF14TOB+mqhDesE0n7/s4Ao6szg2NUFuFUIW/67k5Ctaig+3RPIpiunjH4MeVeWKbR4W+Dxs8KA==,iv:iZ/8mcTvLVcchJuQ+keezjDhhYSIJ4PkKh+98pZgGa4=,tag:0sEr39MKYSfxIe9yQcaJSA==,type:str]
    GRAFANA_WEBHOOK_TOKEN: ENC[AES256_GCM,data:e2nDVHjnkeAX7c4KWIsi9XChsi+JDJH18Z4BjzUynMlWAB8pujxf1ahL3z1STPqRseYNmH4npZPNq66/QbiDSQ==,iv:tVsRjkrMwVu1T1biBK0AkM/pGAkd1RwXhfRrXiEeVHc=,tag:6Auu28pQ6cilfyMSPmc8ZA==,type:str]
sops:
    age:
        - recipient: age1776wth2d8psy2swdcuw5t5ptj4hdegnjzh2eppz4gahas6waks7q37cf57
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBISW1ZK1duU21RcDBHaW9U
            VHovempmc1A0WXRkaFJnRTJLRVNPL0JhdVYwCmxJdXQzMld3Q3YzRFJrNjZlR0xs
            SjRQZVFtVkhnSDM3TmdiR0orT0l4SGsKLS0tIHE4MTFHYUk5WGJoZXpMNklmU25l
            MkpqR2NHdXhFOFFwNzhZdXFyaXM5RjQKJLD2j+/Phavh+TIZ3cvWHALvmibIP42/
            FNOkG7215lMTw0UETNViZc9K/Mg4cCE1mP9mYFwTB/sSxsgRUgFUaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-16T00:45:53Z"
    mac: ENC[AES256_GCM,data:ADpS4/BL1LOOJPQuLLeoK7Tk6WZhVP0qWwYqBFRKib0hJLpmbmtI9Gufg2RPd5ZtkVtN6AVBdafQAa8WEcPt0TietASw/4Eb6JUfSn9vpBITzvVqURlt0EVfzkN5+4JdsJjtp+Ztm17mADujUyceOqi3AS4eh2NXiMQeBi7h33I=,iv:PCUtOc9ZYRi53tczlrNRe1Xiolv2ls+8aonA3aIAnxM=,tag:VFJbvnoH4uZS4dL2vtutig==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
