# Encrypt with: sops --encrypt --in-place secrets.yaml
apiVersion: v1
kind: Secret
metadata:
    name: nexus-env
    namespace: nexus
type: Opaque
stringData:
    GITHUB_WEBHOOK_SECRET: ENC[AES256_GCM,data:+xjXReIWdcbIGmLbYbvcFA6LKhtQpHIBME+9BgECAmwGSyzLaYofANn6Co9JXpWVkU0KzFR0aQyoVMcBwI8jJg==,iv:OtMdoN3CRaSs2zipNRvCU1SK75Arzs20Toq5K5YBckw=,tag:mZ1BR4ShzhlVTmTQopMKqA==,type:str]
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:o2blH5nwZGsLv2Gjn9HHnIWH1XFoSa0cagW49sZJ9ITLcP8R1rL9sI6wsT98pcVVlTZ3Qm9oarZkpIKeXezs9AHrTdrhh+nsCw==,iv:pnCLvqgu2Q9zrtXf8Glm3E2dWff9ny+17FwLsRZThTY=,tag:Vn3LexZwdnw60E3duosZ4g==,type:str]
    TS_AUTHKEY: ENC[AES256_GCM,data:e2uybM+PDH+Na4yU9BT0fNXhKbu2YlHVm5dXVazPOaZGa9eTcAe344VBFmdakOjJB+IbIBUPh8MdODuzRQ==,iv:fNMx4ToYgrcdiOqn6Q0LYhOpkIT6pyO77kXZxSaNkpc=,tag:Ik1zvB69e/89cdR4gao/gA==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:JSFL4d7FwkxpMGT4JW3t8UcVr/fz4XkWwFLV9NSn4g0WRZQ9AYaakr3aKhl/JulKrkQr79w7zoxtyYKKvfO5nP6OsEfhw4V4fOrkQBrX51YAcUNrt7bho1DdJ3+1zfG6/WDxCNFKyVd3VEGfFutsIYVcLA==,iv:u8kswio2CW0yJ2VWFkowhSAKyAigX3c7oxiCWlBOynM=,tag:idhnLzKjMt6rH5BW5YlsfA==,type:str]
    GRAFANA_WEBHOOK_TOKEN: ENC[AES256_GCM,data:4aufTksWWCLofF938pQEmuR71pukUxvh4Z7yrNlYvA/bbT6Pf3Xyez1G3RHoUbHFzrJKj8I/aPmF8hVy8kMv+Q==,iv:YlAX02dHuXtqYu5eN7wyVe5o9v26gm9DsjshNdqNnUw=,tag:gU+pRyh3q1dZvGEBMDN4Vw==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:SxpDcrds4UjxFOT9RlcRESxlwIHWxEoaLO9/bjfmByXh7THQXprfSVtlv/fwYoLLWzZEsni+OJVgBl8jD6qW+uHJtc3NpxtRkg==,iv:VPqQTMMXxaDhKp5eNsQ9IIVuBiTSL/i2xTJJwJpaCi8=,tag:05cNyg1cV0EUfTg4BzqAEw==,type:str]
sops:
    age:
        - recipient: age1776wth2d8psy2swdcuw5t5ptj4hdegnjzh2eppz4gahas6waks7q37cf57
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4UDBsNlRCSk9HdFJzUmFY
            d3grVWoveHhHYzVFWmd1RW1LZDkyQXlxbUh3CkpBaXd6bWpjaEdVZzIyV1NpNzlp
            eVU1N1RSUnJaY3JtMDJ2WVY4WWF0cHMKLS0tIEFmV0VMM3QrZFRyQ29xL051eUZp
            ejMxVTVtVllSOEcyUUk5cERBY1JoQUUKJdssC+t0stds8hgFEJDudqa+/MJpbX6F
            WTVKlSlwvcZ1EmOxqA1Gfwuui3EklYhYrsnSayVLXBmyVvo9eualEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-16T02:12:22Z"
    mac: ENC[AES256_GCM,data:jzfj6JIIFtu6bZ8VJZ7+dkVpoZIw2GT/HAVorDpZ465ER0uYesLjiQ/+fF95/F6Ohr/ER2PmzUovzj5gGIumxaoyjANeZRajHQCGJK7r0VOHyfg4aU+UrwM381Mtb1MKE1i6UKIpzv5GLDetXCZzPZuOsaQGGrwK9JimPkLv2EA=,iv:iLsUd6RlFxHlRPn9KN8+TDg9T9I/xQbZamEoP3BjLFs=,tag:Yvms6lxxNcnD1S9ZREh1ng==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
