# Encrypt with: sops --encrypt --in-place secrets.yaml
apiVersion: v1
kind: Secret
metadata:
    name: nexus-secrets
    namespace: nexus
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:1MoMuN9aFjVYXRdwV1KlsaAemL9ppBzj2viGBqPvZ16E7ZZrOoaIopgt6dkL42ImLO9/CByn7Mav2RnrK/7lHO+W62hmT1vcg9vtEkiRRBQ6nB0mkw9cXq/7ZH1fp7K9+gtx1FXr+Ee9LV4oHQwnq4cH6h8hQA1u0OkD+ecqlG1xDqR8ozqrS7ICakTS6nlKFkO12z6bYJ/IISG0MKdlxThj8X3eOHW7Dmq4gJIqcryxmPMLRIodKNVoheFV5iugH/1RxnBUsiA3eUKzLGtOD5dmNn5Zz+Q6bQ4hFMPIvjRdHUKeVDFYEwQZiKLxEeh3BNimgFvvXdRpAvWXE2iRbuoVf2fCuS7x0XN8UefW6SuR342klzgnlvrEA90tOkjesmuhnS43Fu6tSiDD9mjWvsYicWo5cfEwsa9svy4yWKUyM6WRszeUIEI3kbMfZI/+XU4KEis36Z3O28G6l+YSVoF66bpKPcvS5twC6LCqHr6/FB8rOHehQ8zaGSZC/8NWIFF1xfWzb98chHaCO1paD1SsAaG4b52biiob8X6UDKcr7rchxHnLXbaeCXKQYLArlgtBzuCw+X+n7tH121a1ldSc9gQ6L7J8eSl4BF3rab9O8Q9ynfrDBZ9jlaRymlI470dM+5bRW7Uu7X2iVRnucpyFsZj+38zh807QwvNPrSGROlCC5vJ9WjNTihwlk+HdRwV1jskZtT2esE4+/BwKxoB3P6aZBX13fN5jHhY0T9JJnvUK4Zq+xIA95VbzO6nZu5eB6YVz2g18PHe3PQxfmVwhNp79Lt1c3hjFnrJneSZiHr1VE9ox2bYp5mtvslm9YU/W6j8UrX6G6Ww+RUzof8sQ3Q/Use2niPbP0QyXwHypTDjwqNO5f/LKCFhvKPlmYBjqyiJXst6fCeWxv1ssDtNEcKuexTavsuDTE5FN8GECbbH/sotF6AO4nP/2GCTcaW12r2wA2obGOivongmBp4ql0LQQjH6sR0JASCOUUyZ5BFyaEpBj42BaEL2nOyggTYNnTVewnJgINeOSI3xzMaL8wHj1xJ43vKeYqclhAa2LvoZalr/ifUC8ziIECtsiVOmYoE5czNT0jEVsVNbexgpfr4fwjW9YOvHYK805NPRwbI3DW2K8A+uatgsSotQERTbqT+obJz0bTUf6QMxxSaI0hwMEeyBv8jyXCporAqvy7u+m0hug0ShlPP9UzTyghJqZzYmIxqUbB+1SeyyqJOimaBDaRCmNTJxPqbO2GJHuSxTDoa8YtZIbmkDb3bEExOSCz7KAhfhEUfMTvEj7aTSM+eUiB/U8nSfYnBon2cYJVuU9uWFQEn5CIKRdkDYJ8d6LI3sOrwKW6mw8kLByK/l7/pqEqArZsRy/LS1RvPV1r3P3tXQqRehaEdpqX6Z89XrXgRaG+/0vl2g27aeyNuXcFCE1SLg5QebtdE+elU9CX4iJVFq/QqZJnOnzBnrFphGXrSyQRLEsiTWTdJQHL0uKTQHeTWJ9vwwgLAZy7nwyHURvTUVzPPE9XiUJWgfhD7BZA34XBG900qXzDhhdqbmskRHObo2fEZ2As1RZxHNbF37bfx8Zv6h3QOAzOrEY4SUp4wZnJZNoZN1azkH2y2Dy9OgNkehhnxR/i9hZ1mpYJE4BtANMOWSo/ErDFtLm7kTvWopsJsFrqTiWf++cQ2UMMTXxQ/0eNzCDsBPxExBVy2H4YNcAbRXJ0XsiKdNlSCyTvp0ZJwPbiSwygM189BSbNOaxkWEKo8gsQ9ZSxY3BqgiIz0nDOXBMpj6qgiZ/z48H8LGU/DZ5MFcxF19CUQ3E2PXwVT6a5SuFJilghhpW5YEr56CnYgx5whFaB+D5v3P3jppQn8SQKyt/L0TsoISmA3QayGwqflbTXkXGqppdScEWPi/mjnty25fIgkxtV5nM3vsaVP7+kNCEiqlaAzxx1T+ZI3bb+xZba6/zAUlVf5Fu+6Oy4kgj/wLr+GFW4VfasxuzR48BtCKpwMRXJqokBLoNnOG+9AaslUCucL69V0dUqLCbpIU4cuJjIGvO6x+KtE8RqQVP92sk8/A/CaiO7xyogYwhRQuZi1PidI3w6A7rOiSRg11arH9/6xy5G9/LKmaSceueGANQW4vdCzcjDghVIUNUV6Qqm3nA5ypys3FpF/unljR89ZRdp00H9uhy+GzwKInDYMgn6NyeQsSQbBR3b4hUlILaNGtIdVsW2/a/mEb6OEIrw1cQySpU75/sRc6OMrpY7rnT0E9Gg2y5GFq2Db57SyrfyqoGmSEO5aPjeTu0Cl6CbTmi7aOmTHvpc91pYyp0Edr6R7uUeZvXYBJxsYM3u3BxxUARDhdywOQFWMo8g2bcPDtVhfN/zLh8h2mQkooXrh0hOP+DBD1Cwjz5agFDqOE0sX3azoO8myOI6LvnvR866JPqn2OQjmaTScCCCJabxQeCRmRnc7B1V7kzeBvUMRpdLs3kveipm8AUMgHSoOzhu9+EOsMHERaYSX3wn8/3fNVEx6DM3prlCGQziJovgPsFYiVxbpOuPOw9qkwbuGWqoNGpbixScs1k0J9ygx3KYsdUnnKtTIuxjMhjRZr6vvEFNk7jUIM02awUXOGS8Tsy2Te/uyMnJ3ibKWbuJcpnhz1X6TAbzPXncNcZiMyUXNkOv8tRX7mOkwEHHbWDKeWt3F8yGgfL5dITXgSIj2zMuOpaISf6sTtClv7WBAN/dswApeLsr4HG/TtXjT99AGNPKI8KERMbr67Ff8l10zvPKosMONPTK+XdtSIGNTi7YUzwEO+gkkcgVUy4rb7fjRn5wy8oMvC1pt1Ck6dJYJVH2Pm5Qm0qoHPGpuhrNOUuwaj7tqaQYL8pzqp9dLa7rN1fIv4GZwYHUEQgmpIYX/MXufxdRoxcrijuxlxSmgzgjujrG1qa/1jmwfXOaTO1/vOxOnQ+TT3Ul1agbmSGj1l3Z4u5G745DxgpH2oZmYLj9bXW4OEIoKPL9rgiUVr+JCQtlp5tf6kliupRY/nm5lYMB1mNtxcFoTuzSfZG6DIBnfe+UCwLROwu30Rl2nuKl6vOCscC+LXoDG6VRtja7hw/2RYfmOLWOucFZtqGfHOse6Wc4SaWkhfqkTbZzBMVW1D5IWLxuAdwXZg9w5eMwO+h3VP6/l194FAOPuDAPjzbEmLoB8ckemfy/zD8zxX9LfWdysnEkKL52NbAj7bFDNJHK68/OgJnpzxkMD1uMErR9Jt99jfZKy8eNLz5LUrN7DdZxyGBEXlZ/686eYGRlP9HCDwK3hasLIrHJcWv+jSTj/aVBhecY6j0swrTGAYMce8I6K6t0fH1m8ug5jqYE14KK6BV0JcQMVlg+c+E+nzwMH5k6dUe,iv:ZH4b4HAzmn5MVm6zPa496imTC71qvohr0CXSqJLjTEw=,tag:3beS7M1U+IxroxtQOjqlfg==,type:str]
sops:
    age:
        - recipient: age1776wth2d8psy2swdcuw5t5ptj4hdegnjzh2eppz4gahas6waks7q37cf57
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjS1NvY1hiMUEyTklKRGJQ
            R1ljQW1sSTZjOVEzRVRrUVdYaUE4cmwrMzNzCjY2clhPOEIzWE9GZDR1YmNCSU9M
            Z2c1YitWaHY3Y05Idk5iazRYaXpEUmsKLS0tIFZBZi9nYTV6clB0Vk95N2FwclBB
            VnZaTXNobUNudmUyNXRVZWJOdXkxME0KJ2eb82ZwR4+Cl4lb2Cy7WN7JOGVSepNt
            vwJ2VUmi3uTXVvq7MYvqiH6WpeFw8DTg4CK7fmHIIqLJPOGWjFK5LA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-14T05:45:29Z"
    mac: ENC[AES256_GCM,data:PbgwDm2kS61vTfpa7WcXoZflldmJJIQ8hjnouyIGzo2BzyHLKh1K7ruzZ0tciQsCitL9PeOwv/r/INkE1X4szR+/9stH3vjhIAJ+XJITbxOvJRD4tlYwFSSZ9tiiPoQ0F8O9ZmqYyYsX4V5Ru2KFvUILDWtKYUmNQV24wWieLJU=,iv:MjkSzquxzKaH8HpAqhIr6S1jDelzzSXVwqlDQcBiZrw=,tag:4uBq6w82y8jfRzi8QvVQ1A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
# Separate secret for env vars (easier to manage)
apiVersion: v1
kind: Secret
metadata:
    name: nexus-env
    namespace: nexus
type: Opaque
stringData:
    GITHUB_WEBHOOK_SECRET: ENC[AES256_GCM,data:3t3M+FBZT9RUkXSPcomN6T4BfvYWu02vizFdIJv0dbximieSiyuEkokRr7UdMdUFOqhF61pzR6/xuep4qQ8jLg==,iv:nfsdMoaJZHVuPlD90/QrqpSaEhCi2RNoqG6vVCJ2h64=,tag:2YBxIqqjej4BfP+3FilPuA==,type:str]
sops:
    age:
        - recipient: age1776wth2d8psy2swdcuw5t5ptj4hdegnjzh2eppz4gahas6waks7q37cf57
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjS1NvY1hiMUEyTklKRGJQ
            R1ljQW1sSTZjOVEzRVRrUVdYaUE4cmwrMzNzCjY2clhPOEIzWE9GZDR1YmNCSU9M
            Z2c1YitWaHY3Y05Idk5iazRYaXpEUmsKLS0tIFZBZi9nYTV6clB0Vk95N2FwclBB
            VnZaTXNobUNudmUyNXRVZWJOdXkxME0KJ2eb82ZwR4+Cl4lb2Cy7WN7JOGVSepNt
            vwJ2VUmi3uTXVvq7MYvqiH6WpeFw8DTg4CK7fmHIIqLJPOGWjFK5LA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-14T05:45:29Z"
    mac: ENC[AES256_GCM,data:PbgwDm2kS61vTfpa7WcXoZflldmJJIQ8hjnouyIGzo2BzyHLKh1K7ruzZ0tciQsCitL9PeOwv/r/INkE1X4szR+/9stH3vjhIAJ+XJITbxOvJRD4tlYwFSSZ9tiiPoQ0F8O9ZmqYyYsX4V5Ru2KFvUILDWtKYUmNQV24wWieLJU=,iv:MjkSzquxzKaH8HpAqhIr6S1jDelzzSXVwqlDQcBiZrw=,tag:4uBq6w82y8jfRzi8QvVQ1A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
