apiVersion: v1
kind: Secret
metadata:
    name: ddns-env
    namespace: ddns
stringData:
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:y73wvqDkq+gpz81c6+qe4Cjv59Kit9jWnUbH7oFjXyukzFpvozE0bNWotQcgh7i/oLkuGG8=,iv:Huf18eCEUZXP4TBRXkx0MgoJrU4QcHPVo3n2c3SO4/o=,tag:0kTW8SdTnuAN/4D0rYdAcQ==,type:str]
sops:
    age:
        - recipient: age1776wth2d8psy2swdcuw5t5ptj4hdegnjzh2eppz4gahas6waks7q37cf57
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1Ymhnd3NkQUdSUkd1VkNi
            RncxZFgzYnhlRVhKb29LaGxBY29RV1JvczJJCjk2OTdveG9HTW1VZGlsVmYzYm1s
            QkJWWmI5V3FGYXlhM0R5RmZXRnBMR2cKLS0tIDJtbmN1YXU5d1MwTWZOZ2ZwVnh6
            NWlMOTdNODVtL3RYb0JrZGlqZXdHLzQKmMdSuYTqVspyiXWAb+eckrx8qjPyFMMl
            XcHCfqNpihe5FX+gv4idXkUM+qWO4yIv71zL9d9133e6IR2e7DTZxw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-02T21:56:37Z"
    mac: ENC[AES256_GCM,data:pxn0uccitrrzA1OENsQSBnrQdQB120rvkXPdszIYjHBDJiJLV8tgMFEIo9kP30I+Tyx0m4Lw6StC6KcHnIYSNbzX7G1PbRxstvhs4DBd1yG+uzFYVa1NQ+0Qk6P5DdAeY724qYnqpQ887TCquo/f3lUEpeswBIYwlQqMHJokP3I=,iv:7SLk6FKLdbety567nTE0nJPAAq7swlyfUeGqqQiShLI=,tag:fmDFblKhIqLdRSTL1NYkLw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
