apiVersion: v1
kind: Secret
metadata:
    name: media-mcp-env
    namespace: hermes
stringData:
    JELLYSEERR_API_KEY: ENC[AES256_GCM,data:F18ixRnos4FeXXZjYJHYtHrA+MIy6So46QjNg3g/H4kdVJJzwKib6Z/UEevVShYfFc2ePuZTjHVmBVbcKN4OYp3g7ig=,iv:zpI4TbORYIaEppDC4tzOkirtSeEkjII5b5/+USZpoTo=,tag:r2nzqQ7V8E00hk5MZ2fiog==,type:str]
    SABNZBD_API_KEY: ENC[AES256_GCM,data:KV9gaxhMy6gjsPktMmn5CxuhVgybzicf8lezn9XVQ8g=,iv:SjOL4zr55S+7UcIevv09v4+RKj/H4Mvzp0/XufjSjzU=,tag:psmH+FHM2WorbEPF0LoIYQ==,type:str]
    JELLYFIN_API_KEY: ENC[AES256_GCM,data:1DoHJiu15vZkDmSnrk2A3Xil2l+nBUj0ocsQQsaZhWc=,iv:ByZOiVUjWW4kwKBll/weHZZSPVzvoGCvfoU67JdiMvc=,tag:NCrpnt4aUOB7x3hJYBoLAg==,type:str]
sops:
    age:
        - recipient: age1776wth2d8psy2swdcuw5t5ptj4hdegnjzh2eppz4gahas6waks7q37cf57
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqTzVsZkNKYkQ3VGc2eEFI
            SmRCdTdwR3A4V2RaVFZIU3FGeEcvSjQ3cldZCk5hWHFFSlFCakUweVVnY1YwZXlw
            SC9uYTlIZ25mL2FBQ3Z0eE5RNG9JMkEKLS0tICtzdm42NzFaRDFOSUlGZE5pUDhl
            SjQ5ak1vVk9XQzVKeThOM1gwYzNtcHcKpOi85N6nzbXKRFTyJ535eXRtn6hdsO12
            N529CGTbfAdign17ee2jDExNWPiFskp+0om7zzFkRUPK/w95EAKiTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-08T01:15:23Z"
    mac: ENC[AES256_GCM,data:LRf9qCRAI/+vqFH7c/8YPqx5xpBYqrGPRV/1mtScB85o+Yh/uT1GSoniyUc+9MZmVk8RH9ShqM/3BwCfbn1ZhhN53G5mSqerKv82ffsg6uE1Hlmka1TWQPfaoQq3jFr6aq72JE5HiF48KDudl8/XFHfCMSM+fssdV1M+D0PHiuQ=,iv:BG0jlTxuj5sqW0LJ8kUewaWeny8+4JBkSD23SrPy9F4=,tag:5TORF1UK02VPXB5+YH9paA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
