apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-external-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  sources:
    - repoURL: https://charts.external-secrets.io
      chart: external-secrets
      targetRevision: "2.0.1"
      helm:
        releaseName: external-secrets
        valueFiles:
          - $values/argocd/clusters/superbloom/infra/external-secrets/values.yaml
    - repoURL: https://github.com/saavy1/sb.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/saavy1/sb.git
      targetRevision: main
      path: argocd/clusters/superbloom/infra/external-secrets/resources
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
