apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-buildkit
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: buildkit
  sources:
    - repoURL: https://github.com/saavy1/sb.git
      targetRevision: main
      path: argocd/clusters/superbloom/infra/buildkit/resources
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
