apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kargo
  namespace: flux-system
spec:
  type: oci
  interval: 30m
  url: oci://ghcr.io/akuity/kargo-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kargo
  namespace: kargo
spec:
  interval: 5m
  chart:
    spec:
      chart: kargo
      version: "1.9.3"
      sourceRef:
        kind: HelmRepository
        name: kargo
        namespace: flux-system
  install:
    createNamespace: true
  values:
    api:
      enabled: true
      host: kargo.saavylab.dev
      adminAccount:
        enabled: true
      secret:
        name: kargo-api-secret
      tls:
        enabled: false
        terminatedUpstream: true
    externalWebhooksServer:
      enabled: false
    webhooks:
      register: false
    webhooksServer:
      enabled: false
    controller:
      argocd:
        integrationEnabled: true
        namespace: argocd
