apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nexus-mc-monitor
  namespace: nexus
spec:
  suspend: true
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: "4.1.1"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        # Single replica - no need to scale the monitor
        replicas: 1
        containers:
          main:
            image:
              repository: ghcr.io/saavy1/nexus-mc-monitor
              tag: latest
              pullPolicy: Always
            env:
              NODE_ENV: production
              # OpenTelemetry
              OTEL_EXPORTER_OTLP_ENDPOINT: http://grafana-k8s-monitoring-alloy-receiver.alloy:4318
              # Valkey for pub/sub
              VALKEY_URL: redis://valkey.valkey.svc.cluster.local:6379
              # Minecraft server - in-cluster service
              MC_LOADBALANCER_HOST: minecraft.game-servers.svc.cluster.local
            # No probes needed - simple polling service
            envFrom:
              - secretRef:
                  name: nexus-env
    # No service needed - doesn't expose HTTP
    service:
      main:
        enabled: false
