apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nexus-env
  namespace: nexus
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: nexus-env
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: GITHUB_WEBHOOK_SECRET
      remoteRef:
        key: GITHUB_WEBHOOK_SECRET
    - secretKey: OPENROUTER_API_KEY
      remoteRef:
        key: OPENROUTER_API_KEY
    - secretKey: TS_AUTHKEY
      remoteRef:
        key: TS_AUTHKEY
    - secretKey: DATABASE_URL
      remoteRef:
        key: DATABASE_URL
    - secretKey: GRAFANA_WEBHOOK_TOKEN
      remoteRef:
        key: GRAFANA_WEBHOOK_TOKEN
    - secretKey: CURSEFORGE_API_KEY
      remoteRef:
        key: CURSEFORGE_API_KEY
    - secretKey: JELLYSEERR_API_KEY
      remoteRef:
        key: JELLYSEERR_API_KEY
    - secretKey: SABNZBD_API_KEY
      remoteRef:
        key: SABNZBD_API_KEY
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nexus-bot-env
  namespace: nexus
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: nexus-bot-env
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: DISCORD_TOKEN
      remoteRef:
        key: DISCORD_TOKEN
    - secretKey: DISCORD_CLIENT_ID
      remoteRef:
        key: DISCORD_CLIENT_ID
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nexus-kargo-git-creds
  namespace: nexus
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: nexus-git-creds
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      metadata:
        labels:
          kargo.akuity.io/cred-type: git
  data:
    - secretKey: repoURL
      remoteRef:
        key: KARGO_GIT_REPO_URL
    - secretKey: username
      remoteRef:
        key: KARGO_GIT_USERNAME
    - secretKey: password
      remoteRef:
        key: KARGO_GIT_PASSWORD
