apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nexus-env
  namespace: nexus
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: infisical-nexus
    kind: ClusterSecretStore
  target:
    name: nexus-env
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: GITHUB_WEBHOOK_SECRET
      remoteRef:
        key: GITHUB_WEBHOOK_SECRET
    - secretKey: OPENROUTER_API_KEY
      remoteRef:
        key: OPENROUTER_API_KEY
    - secretKey: TS_AUTHKEY
      remoteRef:
        key: TS_AUTHKEY
    - secretKey: DATABASE_URL
      remoteRef:
        key: DATABASE_URL
    - secretKey: GRAFANA_WEBHOOK_TOKEN
      remoteRef:
        key: GRAFANA_WEBHOOK_TOKEN
    - secretKey: CURSEFORGE_API_KEY
      remoteRef:
        key: CURSEFORGE_API_KEY
    - secretKey: JELLYSEERR_API_KEY
      remoteRef:
        key: JELLYSEERR_API_KEY
    - secretKey: SABNZBD_API_KEY
      remoteRef:
        key: SABNZBD_API_KEY
    - secretKey: INFISICAL_API_TOKEN
      remoteRef:
        key: INFISICAL_API_TOKEN
    - secretKey: GRAFANA_API_KEY
      remoteRef:
        key: GRAFANA_API_KEY
    - secretKey: GITHUB_PAT
      remoteRef:
        key: GITHUB_PAT
    - secretKey: INFISICAL_CLIENT_ID
      remoteRef:
        key: INFISICAL_CLIENT_ID
    - secretKey: INFISICAL_CLIENT_SECRET
      remoteRef:
        key: INFISICAL_CLIENT_SECRET
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nexus-bot-env
  namespace: nexus
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: infisical-nexus
    kind: ClusterSecretStore
  target:
    name: nexus-bot-env
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: DISCORD_TOKEN
      remoteRef:
        key: DISCORD_TOKEN
    - secretKey: DISCORD_CLIENT_ID
      remoteRef:
        key: DISCORD_CLIENT_ID
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nexus-kargo-git-creds
  namespace: nexus
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: infisical-nexus
    kind: ClusterSecretStore
  target:
    name: nexus-git-creds
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      metadata:
        labels:
          kargo.akuity.io/cred-type: git
  data:
    - secretKey: repoURL
      remoteRef:
        key: KARGO_GIT_REPO_URL
    - secretKey: username
      remoteRef:
        key: KARGO_GIT_USERNAME
    - secretKey: password
      remoteRef:
        key: KARGO_GIT_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nexus-kargo-image-creds
  namespace: nexus
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: infisical-nexus
    kind: ClusterSecretStore
  target:
    name: nexus-image-creds
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      engineVersion: v2
      metadata:
        labels:
          kargo.akuity.io/cred-type: image
      data:
        repoURL: ^(registry\.saavylab\.dev|zot\.zot\.svc\.cluster\.local:5000)/saavy1/(nexus|nexus-bot|nexus-agent-worker|nexus-mc-monitor)$
        repoURLIsRegex: "true"
        username: '{{ .username }}'
        password: '{{ .password }}'
  data:
    - secretKey: username
      remoteRef:
        key: ZOT_USERNAME
    - secretKey: password
      remoteRef:
        key: ZOT_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nexus-registry-pull
  namespace: nexus
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: infisical-nexus
    kind: ClusterSecretStore
  target:
    name: nexus-registry-pull
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
      data:
        .dockerconfigjson: >-
          {"auths":{"registry.saavylab.dev":{"username":"{{ .username }}","password":"{{ .password }}","auth":"{{ printf "%s:%s" .username .password | b64enc }}"}}}
  data:
    - secretKey: username
      remoteRef:
        key: ZOT_USERNAME
    - secretKey: password
      remoteRef:
        key: ZOT_PASSWORD
