apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: infisical
spec:
  provider:
    infisical:
      hostAPI: http://infisical.infisical.svc.cluster.local:8080
      auth:
        tokenAuthCredentials:
          accessToken:
            name: infisical-token-auth
            key: accessToken
            namespace: infisical
      secretsScope:
        projectSlug: nexus
        environmentSlug: dev
