apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: nexus
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: nexus-images
      sources:
        direct: true
  promotionTemplate:
    spec:
      vars:
        - name: gitRepo
          value: https://github.com/saavy1/sb.git
        - name: targetBranch
          value: main
      steps:
        - uses: git-clone
          config:
            repoURL: ${{ vars.gitRepo }}
            checkout:
              - branch: ${{ vars.targetBranch }}
                path: ./work
        - uses: yaml-update
          config:
            path: ./work/argocd/clusters/superbloom/nexus/api/values.yaml
            updates:
              - key: controllers.main.initContainers.db-migrate.image.digest
                value: ${{ imageFrom("ghcr.io/saavy1/nexus").Digest }}
              - key: controllers.main.containers.main.image.digest
                value: ${{ imageFrom("ghcr.io/saavy1/nexus").Digest }}
        - uses: yaml-update
          config:
            path: ./work/argocd/clusters/superbloom/nexus/bot/values.yaml
            updates:
              - key: controllers.main.containers.main.image.digest
                value: ${{ imageFrom("ghcr.io/saavy1/nexus-bot").Digest }}
        - uses: yaml-update
          config:
            path: ./work/argocd/clusters/superbloom/nexus/agent-worker/values.yaml
            updates:
              - key: controllers.main.containers.main.image.digest
                value: ${{ imageFrom("ghcr.io/saavy1/nexus-agent-worker").Digest }}
        - uses: yaml-update
          config:
            path: ./work/argocd/clusters/superbloom/nexus/embeddings-worker/values.yaml
            updates:
              - key: controllers.main.containers.main.image.digest
                value: ${{ imageFrom("ghcr.io/saavy1/nexus-embeddings-worker").Digest }}
        - uses: yaml-update
          config:
            path: ./work/argocd/clusters/superbloom/nexus/mc-monitor/values.yaml
            updates:
              - key: controllers.main.containers.main.image.digest
                value: ${{ imageFrom("ghcr.io/saavy1/nexus-mc-monitor").Digest }}
        - uses: git-commit
          config:
            path: ./work
            message: "chore(kargo): promote nexus images to ${{ ctx.stage }}"
        - uses: git-push
          as: push
          config:
            path: ./work
            targetBranch: ${{ vars.targetBranch }}
            provider: github
        - uses: argocd-update
          config:
            apps:
              - name: nexus-api
                namespace: argocd
                sources:
                  - repoURL: ${{ vars.gitRepo }}
                    desiredRevision: ${{ outputs.push.commit }}
              - name: nexus-bot
                namespace: argocd
                sources:
                  - repoURL: ${{ vars.gitRepo }}
                    desiredRevision: ${{ outputs.push.commit }}
              - name: nexus-agent-worker
                namespace: argocd
                sources:
                  - repoURL: ${{ vars.gitRepo }}
                    desiredRevision: ${{ outputs.push.commit }}
              - name: nexus-embeddings-worker
                namespace: argocd
                sources:
                  - repoURL: ${{ vars.gitRepo }}
                    desiredRevision: ${{ outputs.push.commit }}
              - name: nexus-mc-monitor
                namespace: argocd
                sources:
                  - repoURL: ${{ vars.gitRepo }}
                    desiredRevision: ${{ outputs.push.commit }}
