apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: nexus
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: nexus-images
      sources:
        direct: true
  promotionTemplate:
    spec:
      vars:
        - name: gitRepo
          value: https://github.com/saavy1/sb.git
        - name: targetBranch
          value: main
      steps:
        - uses: git-clone
          config:
            repoURL: ${{ vars.gitRepo }}
            checkout:
              - branch: ${{ vars.targetBranch }}
                path: ./work
        - uses: yaml-update
          config:
            path: ./work/argocd/clusters/superbloom/nexus/api/values.yaml
            updates:
              - key: controllers.main.initContainers.db-migrate.image.tag
                value: ${{ imageFrom("zot.zot.svc.cluster.local:5000/saavy1/nexus").Tag }}
              - key: controllers.main.containers.main.image.tag
                value: ${{ imageFrom("zot.zot.svc.cluster.local:5000/saavy1/nexus").Tag }}
        - uses: yaml-update
          config:
            path: ./work/argocd/clusters/superbloom/nexus/bot/values.yaml
            updates:
              - key: controllers.main.containers.main.image.tag
                value: ${{ imageFrom("zot.zot.svc.cluster.local:5000/saavy1/nexus-bot").Tag }}
        - uses: yaml-update
          config:
            path: ./work/argocd/clusters/superbloom/nexus/agent-worker/values.yaml
            updates:
              - key: controllers.main.containers.main.image.tag
                value: ${{ imageFrom("zot.zot.svc.cluster.local:5000/saavy1/nexus-agent-worker").Tag }}
        - uses: yaml-update
          config:
            path: ./work/argocd/clusters/superbloom/nexus/mc-monitor/values.yaml
            updates:
              - key: controllers.main.containers.main.image.tag
                value: ${{ imageFrom("zot.zot.svc.cluster.local:5000/saavy1/nexus-mc-monitor").Tag }}
        - uses: git-commit
          config:
            path: ./work
            message: "chore(kargo): promote nexus images to ${{ ctx.stage }}"
        - uses: git-push
          as: push
          config:
            path: ./work
            targetBranch: ${{ vars.targetBranch }}
            provider: github
