apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: nexus-images
  namespace: nexus
spec:
  freightCreationPolicy: Automatic
  subscriptions:
    - image:
        repoURL: zot.zot.svc.cluster.local:5000/saavy1/nexus
        imageSelectionStrategy: Lexicographic
        allowTags: ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$
    - image:
        repoURL: zot.zot.svc.cluster.local:5000/saavy1/nexus-bot
        imageSelectionStrategy: Lexicographic
        allowTags: ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$
    - image:
        repoURL: zot.zot.svc.cluster.local:5000/saavy1/nexus-agent-worker
        imageSelectionStrategy: Lexicographic
        allowTags: ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$
    - image:
        repoURL: zot.zot.svc.cluster.local:5000/saavy1/nexus-mc-monitor
        imageSelectionStrategy: Lexicographic
        allowTags: ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$
