apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: radarr
  namespace: radarr
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: "4.1.1"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        strategy: Recreate
        containers:
          main:
            image:
              repository: linuxserver/radarr
              tag: latest
              pullPolicy: IfNotPresent
            env:
              TZ: America/Denver
              PUID: "1000"
              PGID: "100"
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                cpu: 1000m
                memory: 1Gi
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: 7878
                  initialDelaySeconds: 30
                  periodSeconds: 10
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: 7878
                  initialDelaySeconds: 10
                  periodSeconds: 5
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: 7878
                  initialDelaySeconds: 15
                  failureThreshold: 30
                  periodSeconds: 5
    service:
      main:
        controller: main
        ports:
          http:
            port: 7878
    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 5Gi
        storageClass: local-path
        globalMounts:
          - path: /config
      downloads:
        enabled: true
        type: hostPath
        hostPath: /srv/downloads
        globalMounts:
          - path: /downloads
      media:
        enabled: true
        type: hostPath
        hostPath: /tank/media
        globalMounts:
          - path: /media
