apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nexus-agent-worker
  namespace: nexus
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: "4.1.1"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        # Single replica for now - can scale later if needed
        replicas: 1
        serviceAccount:
          name: nexus
        containers:
          main:
            image:
              repository: ghcr.io/saavy1/nexus-agent-worker
              tag: latest
              pullPolicy: Always
            env:
              NODE_ENV: production
              # Tailscale SSH - uses hostname, no keys needed
              OPS_SSH_HOST: superbloom
              OPS_SSH_USER: saavy
              OPS_FLAKE_PATH: /home/saavy/dev/sb
              OPS_FLAKE_TARGET: superbloom
              # External services
              VALKEY_URL: redis://valkey.valkey.svc.cluster.local:6379
              QDRANT_URL: http://qdrant.qdrant.svc.cluster.local:6333
            envFrom:
              - secretRef:
                  name: nexus-env
            # No HTTP probes - worker doesn't expose HTTP
          # Tailscale sidecar for network access (needed for SSH ops)
          tailscale:
            image:
              repository: ghcr.io/tailscale/tailscale
              tag: v1.78.1
            env:
              TS_HOSTNAME: nexus-agent-worker
              TS_STATE_DIR: /var/lib/tailscale
              TS_USERSPACE: "true"
              TS_SOCKET: /var/run/tailscale/tailscaled.sock
              TS_KUBE_SECRET: nexus-agent-worker-tailscale
              TS_AUTHKEY:
                valueFrom:
                  secretKeyRef:
                    name: nexus-env
                    key: TS_AUTHKEY
            securityContext:
              runAsUser: 0
              runAsGroup: 0
    # No service needed - doesn't expose HTTP
    service:
      main:
        enabled: false
    persistence:
      tailscale-state:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /var/lib/tailscale
      tailscale-socket:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /var/run/tailscale
