apiVersion: v1
kind: Secret
metadata:
    name: spark-bot-env
    namespace: spark-bot
stringData:
    DISCORD_TOKEN: ENC[AES256_GCM,data:giqV+sjTGJboFn8eSg0pw45oMrGB/HflWuLUD+G06ILzfPI+e+GjUP8CkQ+3TcBgV9FK/cVGyhU+OzTXAkkssW44L5+M2bIF,iv:UmoiZ8Od6PQt5c/bGqhK6B1a61B/HI3e5ptmISZeLLc=,tag:yD5noGRkkA9vu9qNvYH0Bg==,type:str]
    ALLOWED_USERS: ENC[AES256_GCM,data:nJ8MnjaJv0ABjL2twewJ0B2x,iv:dJV/Lx7xOpZ03gl8CJBQcv82aDUESNrPepp8L7fQFic=,tag:IPQxtAxEeIY4elrBKaSpdw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKRnZka3Nkb2hHL3lTRXVN
            MG8reFBqK29NNVJicjBXK3V4V2cxNElhVkIwCk4yVjg2clVROVB0VGJDQWR6cGJM
            VnBvUUZDTEh6UHV6TGQ3cjBydVZuYzQKLS0tIHo3YVJpVU5mUFVDSGc4MG5lbE9V
            eEdqWkNndWtPQnpienpSa1FtQWlRNncKcOPWEnJ80uDqzGUluQk+tBMEYuZ3SuaF
            Ni4FZjAiOyVvhwCrGOQfRx2SDC4Epd+CDUOibj8rtNRdG44UPxmclw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1776wth2d8psy2swdcuw5t5ptj4hdegnjzh2eppz4gahas6waks7q37cf57
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T06:35:55Z"
    mac: ENC[AES256_GCM,data:dW4HS+rkMoOLw+w7Qo8JsTWKMjnWuaAPr55wSD9aFNuoglOLirCpVUp9VV/rOMzg/JoSNsM8WWhg9xo/A4X/qEp7mg0utKqouW+cTJBVS/yEovgGvo4Bap6QiaYAsF7jXaolawigy55DybicXANsQpOnKW89FTDDyh5SyEEIzMU=,iv:Vi3Nr7L1vPZHBg+O0HkBP3eLJmeN3y5R1/iHNx3C67k=,tag:1hfaKyAISFHhPTCbL3/euQ==,type:str]
    version: 3.13.3
