apiVersion: ENC[AES256_GCM,data:9Vc=,iv:cTgMjBLn6Qx0hHz3G2NGim82DOZyn1ybNG6viviSyNo=,tag:Rcjzq4ajMdrYhX/HT+v7sw==,type:str]
kind: ENC[AES256_GCM,data:h/3WMseQ,iv:WWdOaMUsZvDK/l5qM0xBHCWTIMddh3UIErne4XBAec8=,tag:5yWhoiTb278DNJ4IeBwO6A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:DaK1z0kOUpsI7QaLeT3Mwg==,iv:Z7Tw/l5UjrIyA26dSvZoSi6eXftVcCwlhNDsVzbpffM=,tag:lUjAWXo8OGbRSwp5mCPl6A==,type:str]
    namespace: ENC[AES256_GCM,data:kXbaoTo8+f4=,iv:JhumJzWAtM25k4HJBxoifOdPeZKHoiuwccSoJe55xVQ=,tag:0JORBs+NrgkgsPLj9ovLMg==,type:str]
stringData:
    identity_validation.reset_password.jwt.hmac.key: ENC[AES256_GCM,data:ZptpcmUTk70eGo4iQRT7cQEUI3GrysfXmBpj9C4=,iv:pGu9VUoXemJwwI1NIy+tvZT/ggV+HUUmH8E5gS6MRd0=,tag:3zKsNlVEqbUe8mmpvy0QKg==,type:str]
    session.encryption.key: ENC[AES256_GCM,data:ZwEP07xWfjan3O2Uqp9fTE4snf6Ii4DDI8gXzE0=,iv:ydAcVToQchQD6PEAhbozgIk4cy3zUtcdkOwLWHPHCiQ=,tag:MUMKs/0XSfDp/Fq30TYm5g==,type:str]
    storage.encryption.key: ENC[AES256_GCM,data:yvl84h5h3gRkFtHBU6jhXClxvlvaBsOGXYTnjEQ=,iv:5Ib2IjTijrcyX4UT9pfARUNjhhvrKeoajUPvrZR+krk=,tag:uHOjEMZI1Vgn5FJTO+lLmQ==,type:str]
    jwt.token.hmac.key: ENC[AES256_GCM,data:DWsZgK0kKgzx9b37EeMmidsC2taz8jPRF/bPXao=,iv:1NFjHc2JX7OJnl6NrtCGfgFizlW+a7iSq2cOZFiYWl4=,tag:9WlkZ/5pCMYavhzOuEnm5g==,type:str]
sops:
    age:
        - recipient: age1776wth2d8psy2swdcuw5t5ptj4hdegnjzh2eppz4gahas6waks7q37cf57
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEN2cxdnB3M3ZOSTZMd0Vl
            UzdvZE5EVVVGTEVQdUxmT093Sm1ubk5vVlQ0CmY1eit0SG84bklxK2dTM2FIcXZ4
            RDUvM0RJVklrQlFibktVMU1rM2VCWWsKLS0tIEZCcG40b2d5OWFjN2Vqam10cFc3
            aEVqd0grZnBRRnZRNHEyeFE4MW9HemsK7AwiiL5W/Leu1EJ6uzYgGbysxMu2t0zT
            nf3yVZ9F4vLZJxydxoARlfHsVSjdfN7Yj3R2xIo0HDQJH+j8VdSJ/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-02T20:53:14Z"
    mac: ENC[AES256_GCM,data:6/3uLE3cazpvonNbj9doQDaOWXJm4KPEbNLUwZt9qfi8Pbzqg2oVvIQeUrq9YX4p6cHNr09W4++ByaI2FM+khkB0JTHrCRzCuJ75DHb1yjjJ9k6dPfGcFygrXvFuwWAZWy9Dkyui7BZP5NtWYV8NAuUPRs4PKf4ApOOKuEkV25Q=,iv:diQrFiFkorNN0VGhaKiPl5MusDwOZUo+Ya5sPcN2fRM=,tag:Z+XAVroASzlI+gG5ZqnTyA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
