apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:b9ejh6tvM30J2PdZ9FJHH26kOM7oQUWDXV3BNqZ4Cs3uau+sbfXQF/wIi7yAdj/UAW9bfM7FwG9owYBVBvrMvGmpX136CBiP+MHk5GL4kKi1VXa7z7Qm3brOhcYZqJEI5LeoAwlXYUz1GjmAHPIKO9NOPOEaNvh9DKHvZ8AVcx5I9+RxitI/tqgRhCR8ma81bSAa4BbtbG3mA/pKJGdPWrngxaUmUPumVv7V76h4eVDJceQgZ1XjIyaeEHDIc/UGkyCDl9i2K5oIp9FpqwTIAehJ47edOm9wnPyeRxJp6XMZwBtQbFFqtjFZShZTqYAVHGeC/G5fAB7NXK3apawR+g==,iv:LxT7CJg/Hnt9kdltgACYPP7kCO5QsIl2XQVm6tq9ipQ=,tag:tNvMZ/SEfzUzPZpT9xjq1g==,type:str]
kind: Secret
metadata:
    name: ghcr-pull
    namespace: hermes
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - recipient: age1776wth2d8psy2swdcuw5t5ptj4hdegnjzh2eppz4gahas6waks7q37cf57
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYRUUwamx6cmNzUFQwNVds
            TDY5eml6cXZrclBFRHJuMEwydDIyZVV5QUFRCkp5MCttM3VWVmplSnJ3Mzh1ZHFk
            U1pwSnBJRzdWaUFIMDVMdHlWVmdtb2MKLS0tIHdWZ3Q5Mkt6SzJUdEtNSlM1SEZE
            MFJsSkFhbG41R0c5eGppaVJvUE1iRWcKyc8d6PtrJwjx+V9sqp3Ac8FKoizNVf8d
            3sgycXK+/8K6h9zWSDRihBB6TBiLxs3mrIEDsQjr2EjZIgf1CE4Niw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-02T22:05:33Z"
    mac: ENC[AES256_GCM,data:zslabngwx1KMn6FcijF6hoM7Mxb1q3UUaOL1QQkIN8BSkeQuQkfdLH2jsADIN5yTK8PAhWU7oW3H4WCSoLUeSMxFsSt6Wo6suhTbVa3YfNWbFivh85A7jhoVpA7mcguG/HbJsbv3RfInblkDTbp8KM2NzwgLkUGezUURKmcK1hA=,iv:ejH6ruD53tO0RvWgYtxGhzXB6W8M8OaGnVYRfrMeEzI=,tag:9Sj1TPFplmNXdGamqvow7Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
