apiVersion: v1
kind: Secret
metadata:
    name: hermes-env
    namespace: hermes
stringData:
    DISCORD_TOKEN: ENC[AES256_GCM,data:DN8T2jFF07QpudR2qWte8LkKb5/5nVVmyejY9Gexv4u8IeGC828u6SAUiqzI7YsO6BfJZYeXDyjGdz0Zmw00OZPtm4e264sU,iv:Arfjsj6eSu1AI7QtJoVkh9PHLDBITWwLh2xjAtmpvUE=,tag:jtsC0Pa+i4T6XJSemj+uAw==,type:str]
    DEEPSEEK_API_KEY: ENC[AES256_GCM,data:jb0TPaCVABQhzN7CeUN6s45zB2f7PfOeM3xm/GoxKYcsidc=,iv:kMgm/L5PftsMw7Y/IhShSNaevvZ2loxBfMUB12//if4=,tag:SYGpqOQHGU86Fl6iSZWUdQ==,type:str]
    GRAFANA_API_TOKEN: ENC[AES256_GCM,data:5rHWDXwtJ54py1tl8vt+tljSWPg+XyjqXYGmogpie6tHK9kEsS3nCOaJzQjRrQ==,iv:yej0ppGzCsZoa5Paasl4g9S95/S9MlTL4bwvlxC8fZI=,tag:+rG49U1Y3Ib1q1Of1yObxg==,type:str]
sops:
    age:
        - recipient: age1776wth2d8psy2swdcuw5t5ptj4hdegnjzh2eppz4gahas6waks7q37cf57
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnSEJTYnUrUnkwUmRYNVcw
            bDRqLzVxaXhzdC9DY1gxb01VZHlhWVpUZlR3CldSejhENE5SemFEbDZCUWdHQ0VU
            ZG5HcFRVR0RXNlUrb3RDTzFJSlpGRHcKLS0tIGt2azF6cHVXcDBTTWV5M05jREgw
            SzE3TmNlUnJVMHdYNjRkMXp5Zmh2RmcKQsEMWkBe4lmm+Aejl5N5Kyy/eWWAWA5p
            g9DFTlLtBYKpHzMHj8uXpghz15VTkWUdzJyaLBnHIrA57rUkFMVWiw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-03T19:54:53Z"
    mac: ENC[AES256_GCM,data:NMSuEuMOPkv/nV8Lvsps+1L/8IqjXf9JfeTdd/ac9qQ1l8xyUdLLgVDoP1P0ZOLpABrDz3Y+ulsZ92h+uD/vA+VXs/uJe1AcekDEDlO5Ps0XU2zai/gS3XxhTiXHF0jZbAIe7vxJp5a26t5JKFYux5Lj64HV45dWutCE5GNRFYA=,iv:GAs6cChEf1EaqaSvIa9vRoMyp9+TOb9COlrHEOiiPdM=,tag:/4Z39d+fS0OHPOxUh0lCoQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
