apiVersion: v1
kind: Secret
metadata:
    name: hermes-env
    namespace: hermes
stringData:
    DISCORD_TOKEN: ENC[AES256_GCM,data:DN8T2jFF07QpudR2qWte8LkKb5/5nVVmyejY9Gexv4u8IeGC828u6SAUiqzI7YsO6BfJZYeXDyjGdz0Zmw00OZPtm4e264sU,iv:Arfjsj6eSu1AI7QtJoVkh9PHLDBITWwLh2xjAtmpvUE=,tag:jtsC0Pa+i4T6XJSemj+uAw==,type:str]
    DEEPSEEK_API_KEY: ENC[AES256_GCM,data:jb0TPaCVABQhzN7CeUN6s45zB2f7PfOeM3xm/GoxKYcsidc=,iv:kMgm/L5PftsMw7Y/IhShSNaevvZ2loxBfMUB12//if4=,tag:SYGpqOQHGU86Fl6iSZWUdQ==,type:str]
    GRAFANA_API_TOKEN: ENC[AES256_GCM,data:5rHWDXwtJ54py1tl8vt+tljSWPg+XyjqXYGmogpie6tHK9kEsS3nCOaJzQjRrQ==,iv:yej0ppGzCsZoa5Paasl4g9S95/S9MlTL4bwvlxC8fZI=,tag:+rG49U1Y3Ib1q1Of1yObxg==,type:str]
    ARGOCD_API_TOKEN: ENC[AES256_GCM,data:NszojUb2DdC1hLyCh9ct63zcZavNNClNW0A3JqkG2e7QHUl4oqQ/f8Oj0W56fD5hXi4k7Ex2W8wLI92HQIyrX4iHtjyPXaGaHHG6PdLRcUbcWriHnGkkVG0xBF2PARkc6MGnNTeC94bfjFFdMUagg/k6lrzZC5AZU+SeQupJdQld0cOr1b3PjesADm4Xn2ZuMOBHiBCCUOaXPpOgQ8TScv0xC0W0ZTD7gYhgXElb09i+CzyBP/QtxJYOdL0SYnWzkn/5p3vu4TaENpJ0PLUeUA==,iv:GahXB3w8/1jsx+WhYeDABqXWumUs49U/hnvkJD5B8V0=,tag:RGRzrHr+i6hxduoQtcogtg==,type:str]
sops:
    age:
        - recipient: age1776wth2d8psy2swdcuw5t5ptj4hdegnjzh2eppz4gahas6waks7q37cf57
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnSEJTYnUrUnkwUmRYNVcw
            bDRqLzVxaXhzdC9DY1gxb01VZHlhWVpUZlR3CldSejhENE5SemFEbDZCUWdHQ0VU
            ZG5HcFRVR0RXNlUrb3RDTzFJSlpGRHcKLS0tIGt2azF6cHVXcDBTTWV5M05jREgw
            SzE3TmNlUnJVMHdYNjRkMXp5Zmh2RmcKQsEMWkBe4lmm+Aejl5N5Kyy/eWWAWA5p
            g9DFTlLtBYKpHzMHj8uXpghz15VTkWUdzJyaLBnHIrA57rUkFMVWiw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-03T20:22:32Z"
    mac: ENC[AES256_GCM,data:Z0K9A68QmIWtjn+0xWYAiL7glUgynIk7ELIsfrzrrTWI3MIhKQ7Nxc0Pgx01tjbYqMFFk+wYfHoce76nsZBM2JEqYM1UFNEPtdHK+qwyh7k26yukXdZPhLXW8caNMYc3rzxZ0P5db3i6I6JVi/PczHk6dHRgTF4ub2nypVjDevA=,iv:4P/j4Dt/LzLRwdHPyBANwD7livQFAWw+IFEgKNpAR4k=,tag:OMhKxRjGgFRjpsfClNhCag==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
