controllers:
  main:
    replicas: 1
    serviceAccount:
      name: mcp-k8s
    containers:
      main:
        image:
          repository: ghcr.io/containers/kubernetes-mcp-server
          tag: latest
          pullPolicy: Always
        args:
          - --port
          - "8000"
          - --toolsets
          - core,config,helm

serviceAccount:
  mcp-k8s:
    enabled: false

service:
  main:
    controller: main
    ports:
      http:
        port: 8000
