apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nexus-bot
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: nexus
  sources:
    - repoURL: https://bjw-s-labs.github.io/helm-charts
      chart: app-template
      targetRevision: "4.1.1"
      helm:
        releaseName: nexus-bot
        valueFiles:
          - $values/argocd/clusters/superbloom/nexus/bot/values.yaml
    - repoURL: git@github.com:saavy1/sb.git
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
