apiVersion: v1
kind: ConfigMap
metadata:
  name: caddyfile
  namespace: caddy-system
data:
  Caddyfile: |
    # Global options
    {
        email jayson@saavylab.com
    }

    # Authelia portal - no forward_auth (would cause redirect loop)
    auth.saavylab.dev {
        reverse_proxy authelia.authelia.svc.cluster.local:80
    }

    # Nexus dashboard - protected with forward_auth
    nexus.saavylab.dev {
        # GitHub webhook bypasses auth (signature verified in app)
        # Other webhooks (alertmanager, etc.) use internal ClusterIP
        @github_webhook path /webhooks/github
        handle @github_webhook {
            reverse_proxy nexus.nexus.svc.cluster.local:3000
        }

        # Everything else requires auth
        handle {
            forward_auth authelia.authelia.svc.cluster.local:80 {
                uri /api/authz/forward-auth
                copy_headers Remote-User Remote-Groups Remote-Email Remote-Name
            }
            reverse_proxy nexus.nexus.svc.cluster.local:3000
        }
    }

    # Argo Workflows - GitHub webhook bypasses auth, UI stays protected
    workflows.saavylab.dev {
        @github_workflows_webhook path /api/v1/events/argo/nexus-build-push
        handle @github_workflows_webhook {
            reverse_proxy argo-workflows-server.argo.svc.cluster.local:2746
        }

        handle {
            forward_auth authelia.authelia.svc.cluster.local:80 {
                uri /api/authz/forward-auth
                copy_headers Remote-User Remote-Groups Remote-Email Remote-Name
            }
            reverse_proxy argo-workflows-server.argo.svc.cluster.local:2746
        }
    }

    # Argo CD - uses built-in auth
    argocd.saavylab.dev {
        reverse_proxy argocd-server.argocd.svc.cluster.local:80
    }

    # Kargo - protected with forward_auth
    kargo.saavylab.dev {
        forward_auth authelia.authelia.svc.cluster.local:80 {
            uri /api/authz/forward-auth
            copy_headers Remote-User Remote-Groups Remote-Email Remote-Name
        }
        reverse_proxy kargo-api.kargo.svc.cluster.local:80
    }

    # Infisical - protected with forward_auth
    infisical.saavylab.dev {
        forward_auth authelia.authelia.svc.cluster.local:80 {
            uri /api/authz/forward-auth
            copy_headers Remote-User Remote-Groups Remote-Email Remote-Name
        }
        reverse_proxy infisical.infisical.svc.cluster.local:8080
    }

    # Zot registry + ZUI - uses built-in auth
    registry.saavylab.dev {
        reverse_proxy zot.zot.svc.cluster.local:5000
    }

    # Jellyfin - no forward_auth (uses built-in auth, easier for TVs/Xbox)
    watch.saavylab.dev {
        reverse_proxy jellyfin.jellyfin.svc.cluster.local:8096
    }

    # Sonarr - protected with forward_auth
    shows.saavylab.dev {
        forward_auth authelia.authelia.svc.cluster.local:80 {
            uri /api/authz/forward-auth
            copy_headers Remote-User Remote-Groups Remote-Email Remote-Name
        }
        reverse_proxy sonarr.sonarr.svc.cluster.local:8989
    }

    # Radarr - protected with forward_auth
    movies.saavylab.dev {
        forward_auth authelia.authelia.svc.cluster.local:80 {
            uri /api/authz/forward-auth
            copy_headers Remote-User Remote-Groups Remote-Email Remote-Name
        }
        reverse_proxy radarr.radarr.svc.cluster.local:7878
    }

    # SABnzbd - protected with forward_auth
    downloads.saavylab.dev {
        forward_auth authelia.authelia.svc.cluster.local:80 {
            uri /api/authz/forward-auth
            copy_headers Remote-User Remote-Groups Remote-Email Remote-Name
        }
        reverse_proxy sabnzbd.sabnzbd.svc.cluster.local:8080
    }

    # Jellyseerr - no forward_auth (handles own auth, needs public access for requests)
    fbi.saavylab.dev {
        reverse_proxy jellyseerr.jellyseerr.svc.cluster.local:5055
    }

    # Prowlarr - protected with forward_auth
    indexers.saavylab.dev {
        forward_auth authelia.authelia.svc.cluster.local:80 {
            uri /api/authz/forward-auth
            copy_headers Remote-User Remote-Groups Remote-Email Remote-Name
        }
        reverse_proxy prowlarr.prowlarr.svc.cluster.local:9696
    }

    # Bazarr - protected with forward_auth
    subtitles.saavylab.dev {
        forward_auth authelia.authelia.svc.cluster.local:80 {
            uri /api/authz/forward-auth
            copy_headers Remote-User Remote-Groups Remote-Email Remote-Name
        }
        reverse_proxy bazarr.bazarr.svc.cluster.local:6767
    }

    # Grafana - uses built-in auth
    grafana.saavylab.dev {
        reverse_proxy kube-prometheus-stack-grafana.monitoring.svc.cluster.local:80
    }

    # Health endpoint (optional - for k8s probes on the caddy service itself)
    :80 {
        respond /health 200
    }
