apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nexus-worker
  namespace: nexus
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: "4.1.1"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        # Can scale workers horizontally
        replicas: 1
        serviceAccount:
          name: nexus
        containers:
          main:
            image:
              repository: ghcr.io/saavy1/nexus
              tag: latest
              pullPolicy: Always
            securityContext:
              privileged: true
            env:
              NODE_ENV: production
              MODE: worker
              # Tailscale SSH - uses hostname, no keys needed
              OPS_SSH_HOST: superbloom
              OPS_SSH_USER: saavy
              OPS_FLAKE_PATH: /home/saavy/dev/sb
              OPS_FLAKE_TARGET: superbloom
              OTEL_EXPORTER_OTLP_ENDPOINT: http://grafana-k8s-monitoring-alloy-receiver.alloy:4318
              # External services
              VALKEY_URL: redis://valkey.valkey:6379
            envFrom:
              - secretRef:
                  name: nexus-env
            # No HTTP probes for worker - relies on process restart on crash
          # Tailscale sidecar for network access (needed for SSH ops)
          tailscale:
            image:
              repository: ghcr.io/tailscale/tailscale
              tag: latest
            env:
              TS_HOSTNAME: nexus-worker
              TS_STATE_DIR: /var/lib/tailscale
              TS_USERSPACE: "true"
              TS_SOCKET: /var/run/tailscale/tailscaled.sock
              TS_KUBE_SECRET: nexus-worker-tailscale
              TS_AUTHKEY:
                valueFrom:
                  secretKeyRef:
                    name: nexus-env
                    key: TS_AUTHKEY
            securityContext:
              runAsUser: 0
              runAsGroup: 0
    # No service needed - worker doesn't expose HTTP
    service:
      main:
        enabled: false
    persistence:
      dri:
        enabled: true
        type: hostPath
        hostPath: /dev/dri
        advancedMounts:
          main:
            main:
              - path: /dev/dri
      tailscale-state:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /var/lib/tailscale
      tailscale-socket:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /var/run/tailscale
