apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hermes-env
  namespace: hermes
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: sops-store
  target:
    name: hermes-env
  data:
    - secretKey: DISCORD_TOKEN
      remoteRef:
        key: hermes-env
        property: DISCORD_TOKEN
    - secretKey: DEEPSEEK_API_KEY
      remoteRef:
        key: hermes-env
        property: DEEPSEEK_API_KEY
    - secretKey: GRAFANA_API_TOKEN
      remoteRef:
        key: hermes-env
        property: GRAFANA_API_TOKEN
