apiVersion: v1
kind: Secret
metadata:
    name: recyclarr-api-keys
    namespace: recyclarr
type: Opaque
data:
    sonarr-api-key: ENC[AES256_GCM,data:XoUg7RC+Z0YXOhzPFnRmaDa0TpcyGiQuwTjHz/oV4KS/J4hEZigJ1YAPojg=,iv:BsdaenH9Ktc/PyrEHmfTk9lshPztUpoLO+wY3xHRuJI=,tag:NVeOd82cd1INJ+NWxq6Lmg==,type:str]
    radarr-api-key: ENC[AES256_GCM,data:iW9AlvSh2WTQzb6La+69hA6RjSZivaZQcgcNWbg0FdAjZ0eSWt+Veaz85lE=,iv:3akkEgRLHAX5s6bu42ga289Pa7eQ/aVwE1BvVL2RQtM=,tag:4sVpfZS8FO7b3h6JdI6w2A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLVzR2dEhhV1MvTVJ3bjc3
            OGFvMHZqOHZia1Y4Qzk0azFqMXlqNUppTnc4CnNSKzNnV01RSU04RmFPbnM0VS9Z
            UHBNaUI3YTc0dWJQdm5CcFlFUnB3KzAKLS0tIEFoZm5PRVc2WEJFd3NnQmVxOTRt
            YlJiK2tOWDhja0dySFhxOURVQVFOY2sKMWSUe9mxO6C3YzCa2UGKD6FUCrxGtVVX
            wiGnjutYx+GZZ5AyjGHqvC12/0pFJ8ZaedlLvj2KV8iAbqVGssFQ+g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1776wth2d8psy2swdcuw5t5ptj4hdegnjzh2eppz4gahas6waks7q37cf57
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-07T06:45:06Z"
    mac: ENC[AES256_GCM,data:2UfOQH4heUaO8eN8ElT/f3jDOS1/aslWFUQkV5YkwDYiSQFhjy0dXIqD2a6Czd5DKZQYMoPjUfpfpyUEwnxoFHqKmUyU7eN1YIjEiGUcgDvwpCS0IDMuqur2Il3aL9QVMti7pIC383Nx4vzHjxP8n4Z6ZUqvSBAQCGN8scfjLGY=,iv:XBqC6t6xCYAkdMfehYirA5y+H1RpPlwc8/oFlBI7JzE=,tag:kBkv1E56gmepHyG5VLSlPA==,type:str]
    version: 3.13.3
