apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nexus-core
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: nexus
  source:
    repoURL: git@github.com:saavy1/sb.git
    targetRevision: main
    path: argocd/clusters/superbloom/nexus/core/resources
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
